/*
 * ResourceSelectorForm.java
 *
 * Created on July 9, 2003, 11:32 AM
 */

package net.pengo.resource;

/**
 *
 * @author  Smiley
 */
public class ResourceSelectorForm extends javax.swing.JFrame {
    
    /** Creates new form ResourceSelectorForm */
    public ResourceSelectorForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(0, 2, 3, 3));

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel7.setText("Name");
        getContentPane().add(jLabel7);

        jPanel6.setLayout(new java.awt.FlowLayout());

        jTextField3.setColumns(20);
        jTextField3.setText("jTextField1");
        jPanel6.add(jTextField3);

        jButton4.setText("f(x)");
        jPanel6.add(jButton4);

        getContentPane().add(jPanel6);

        jLabel2.setText("Integer Format:");
        getContentPane().add(jLabel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel3.add(jComboBox1);

        getContentPane().add(jPanel3);

        jLabel3.setText("Value:");
        getContentPane().add(jLabel3);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));

        jTextField1.setColumns(20);
        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);

        jButton1.setText("f(x)");
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1);

        jLabel1.setText("Length:");
        getContentPane().add(jLabel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jComboBox2.setEditable(true);
        jPanel2.add(jComboBox2);

        jCheckBox1.setText("Variable length");
        jPanel2.add(jCheckBox1);

        jCheckBox2.setText("Insert to expand");
        jPanel2.add(jCheckBox2);

        getContentPane().add(jPanel2);

        jLabel4.setText("Limits:");
        getContentPane().add(jLabel4);

        jCheckBox3.setText("Set limits");
        jPanel4.add(jCheckBox3);

        jComboBox3.setEditable(true);
        jPanel4.add(jComboBox3);

        jLabel5.setText("to");
        jPanel4.add(jLabel5);

        jComboBox4.setEditable(true);
        jPanel4.add(jComboBox4);

        jButton2.setText("f(x)");
        jPanel4.add(jButton2);

        getContentPane().add(jPanel4);

        jLabel6.setText("Address:");
        getContentPane().add(jLabel6);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jTextField2.setText("jTextField2");
        jPanel5.add(jTextField2);

        jButton3.setText("f(x)");
        jPanel5.add(jButton3);

        getContentPane().add(jPanel5);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    
}
