/*

Qubero, binary editor
http://www.qubero.org
Copyright (C) 2002-2004 Peter Halasz

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

The GNU General Public License is distributed with this application, or is
available at:
- http://www.qubero.org/license.html
- http://www.gnu.org/copyleft/gpl.html
- or by writing to Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. 

*/

/*
 * Test.java
 *
 * Created on 10 December 2004, 03:19
 */

package net.pengo.app;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;
import javax.swing.JPanel;

/**
 *
 * @author Peter Halasz
 */
public class Test extends javax.swing.JFrame {
    
    /** Creates new form Test */
    public Test() {
        initComponents();
        
        JPanel jp = new JPanel() {
            public void paint(Graphics g) {
                super.paint(g);
                paintComponents(g);
            }
            public void paintComponents(Graphics g) {
                super.paintComponents(g);
                Rectangle r = g.getClipBounds();
                g.drawString(r+"", 10,10);
                System.out.println(r);
                
                g.translate(100,100);
                
                r = g.getClipBounds();
                g.drawString(r+"", 10,10);
                System.out.println(r);                
            }
        };
        Dimension size = new Dimension(300,300);
        jp.setMinimumSize(size);
        jp.setMaximumSize(size);
        jp.setSize(size);
        getRootPane().setLayout(new BorderLayout());
        getRootPane().add(jp, BorderLayout.CENTER);
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
