//! The bundled ImHex patterns: that they are here, that they convert, that
//! every one of them carries a licence Qubero may redistribute, and that the
//! README says the gap count each one has today.
//!
//! `crates/core/src/hexpat/bundled.rs` and `crates/core/formats-hexpat/README.md`
//! are both generated by `tools/hexpat_bundle.mjs`, so both can be stale
//! together. The numbers are therefore checked against the conversion itself
//! rather than against each other: a pattern that changed and a script nobody
//! re-ran fail here.

use std::path::PathBuf;

use qubero_core::hexpat::bundled;

/// The only licences a file in `formats-hexpat` may carry. The repository is
/// GPL-2.0 as a whole, so a file that says nothing of its own is under that and
/// may not be here at all.
const ALLOWED: &[&str] = &["MIT", "MPL-2.0"];

#[test]
fn there_are_bundled_patterns_at_all() {
	// The generated table is a `&[]` until the script has been run, and every
	// other test here would pass vacuously over an empty one.
	assert!(bundled::all().len() >= 4, "only {} bundled patterns", bundled::all().len());
	assert!(!bundled::names().is_empty());
}

#[test]
fn every_bundled_pattern_converts() {
	for entry in bundled::all() {
		match bundled::template(entry.id) {
			Some(Ok(_)) => {}
			Some(Err(e)) => panic!("{} does not convert: {e}", entry.source),
			None => panic!("{} is in the table but `template` cannot find it", entry.id),
		}
	}
}

#[test]
fn an_offered_pattern_is_one_a_name_opens() {
	for id in bundled::names() {
		let name = format!("{}{id}", bundled::PREFIX);
		assert!(qubero_core::formats::template(&name).is_some(), "{name} is offered but opens nothing");
	}
}

/// The licence is the whole reason these four and no others are here, so it is
/// checked against the file's own header rather than against the table, which
/// the same script wrote.
#[test]
fn every_bundled_pattern_carries_a_licence_of_its_own() {
	for entry in bundled::all() {
		assert!(ALLOWED.contains(&entry.licence), "{} is tagged {}", entry.source, entry.licence);
		let head: String = entry.text.chars().take(4000).collect();
		let found = match entry.licence {
			"MPL-2.0" => head.contains("Mozilla Public License"),
			"MIT" => head.contains("Permission is hereby granted, free of charge"),
			_ => false,
		};
		assert!(found, "{} is tagged {} but its header does not say so", entry.source, entry.licence);
	}
}

/// No include file is bundled. The `includes/` tree is GPL-2.0 and the
/// converter reaches those names through its own declaration table instead.
#[test]
fn nothing_bundled_came_from_the_include_tree() {
	for entry in bundled::all() {
		assert!(
			entry.source.starts_with("patterns/") && entry.source.ends_with(".hexpat"),
			"{} is not a pattern from patterns/",
			entry.source
		);
	}
}

/// The README is the record of the bundling decision, and a gap count in it
/// that no longer matches is a record of a decision made about another file.
#[test]
fn the_readme_says_the_gap_count_each_bundled_pattern_has() {
	let readme =
		std::fs::read_to_string(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("formats-hexpat").join("README.md"))
			.expect("the README beside the bundled patterns");
	for entry in bundled::all() {
		let converted = bundled::template(entry.id).expect("in the table").expect("converts");
		let row = readme
			.lines()
			.find(|line| line.starts_with(&format!("| `{}` |", entry.id)))
			.unwrap_or_else(|| panic!("the README has no row for {}", entry.id));
		let cells: Vec<&str> = row.split('|').map(str::trim).collect();
		let said: usize = cells.get(4).and_then(|c| c.parse().ok()).unwrap_or_else(|| panic!("no gap count in {row}"));
		assert_eq!(
			said,
			converted.report.gaps.len(),
			"the README says {} has {said} gaps; it has {}. Re-run tools/hexpat_bundle.mjs",
			entry.id,
			converted.report.gaps.len()
		);
	}
}
