//! The bundled Kaitai Struct formats: that they convert, that the README says
//! what they are, that no two of them claim the same dropped file, and that
//! real files read with them.
//!
//! `crates/core/src/ksy/bundled.rs` and `crates/core/formats-ksy/README.md` are
//! both generated by `tools/ksy_bundle.mjs`, which means both can be stale
//! together. So the numbers are checked against the conversion itself rather
//! than against each other: the README's gap count has to be the count the
//! converter produces today, and the table's signature has to be the one the
//! template derives today. A `.ksy` that changed and a script nobody re-ran
//! fail here.

use std::collections::HashMap;
use std::path::PathBuf;

use qubero_core::decode::fixed_bits;
use qubero_core::document::Document;
use qubero_core::eval::Evaluator;
use qubero_core::ksy::bundled;
use qubero_core::source::MemSource;
use qubero_core::template::Ty;

#[test]
fn there_are_bundled_formats_at_all() {
    // The generated table is a `&[]` until the script has been run, and every
    // other test here passes vacuously over an empty one.
    assert!(bundled::all().len() > 50, "only {} bundled formats", bundled::all().len());
    assert!(!bundled::names().is_empty());
}

#[test]
fn every_bundled_format_converts() {
    for entry in bundled::all() {
        match bundled::template(entry.id) {
            Some(Ok(_)) => {}
            Some(Err(e)) => panic!("{} does not convert: {e}", entry.source),
            None => panic!("{} is in the table but `template` cannot find it", entry.id),
        }
    }
}

#[test]
fn an_offered_format_is_one_a_name_opens() {
    for id in bundled::names() {
        let name = format!("{}{id}", bundled::PREFIX);
        assert!(
            qubero_core::formats::template(&name).is_some(),
            "{name} is offered but opens nothing"
        );
    }
}

/// The README is the record of the bundling decision, and a gap count in it
/// that no longer matches is a record of a decision made about another file.
#[test]
fn the_readme_says_the_gap_count_each_bundled_format_has() {
    let readme = std::fs::read_to_string(
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("formats-ksy").join("README.md"),
    )
    .expect("the README beside the bundled .ksy files");
    let mut said: HashMap<&str, usize> = HashMap::new();
    for line in readme.lines() {
        let cells: Vec<&str> = line.split('|').map(str::trim).collect();
        // `| `id` | category | licence | bundled | gaps | sniffs | why |`
        if cells.len() != 9 {
            continue;
        }
        let Some(id) = cells[1].strip_prefix('`').and_then(|c| c.strip_suffix('`')) else { continue };
        let Ok(gaps) = cells[5].parse::<usize>() else { continue };
        said.insert(id, gaps);
    }
    assert!(said.len() > 50, "the README table has {} rows", said.len());
    for entry in bundled::all() {
        let converted = bundled::template(entry.id).expect("in the table").expect("converts");
        let gaps = converted.report.gaps.len();
        match said.get(entry.id) {
            Some(&written) => assert_eq!(
                written, gaps,
                "the README says {} has {written} gaps; it has {gaps}. Re-run `node tools/ksy_bundle.mjs`.",
                entry.id
            ),
            None => panic!("{} is bundled and the README does not list it", entry.id),
        }
    }
}

/// The signature in the table is derived from the converted template, and the
/// table is written by a script. This re-derives it the same way and insists
/// they agree, so a `.ksy` whose first field changed cannot go on claiming
/// files by the magic it used to have.
#[test]
fn the_table_signature_is_the_one_the_template_derives() {
    for entry in bundled::all() {
        let converted = bundled::template(entry.id).expect("in the table").expect("converts");
        let derived = derive(&converted.template.root);
        let written: Vec<(u64, Vec<u8>)> =
            entry.signature.iter().map(|(at, b)| (*at, b.to_vec())).collect();
        assert_eq!(derived, written, "{}'s signature is stale", entry.id);
    }
}

/// A one-byte magic claims every file whose first byte happens to match, which
/// is a guess dressed as an answer. Anything shorter than two bytes is not
/// offered for a dropped file.
#[test]
fn nothing_sniffs_on_less_than_two_bytes() {
    for entry in bundled::all() {
        if !entry.sniffs {
            continue;
        }
        let bytes: usize = entry.signature.iter().map(|(_, b)| b.len()).sum();
        assert!(bytes >= 2, "{} sniffs on {bytes} byte(s)", entry.id);
    }
}

/// Two bundled formats that would both claim the same file must both stay out
/// of the sniff table: which of them a reader wanted is not something the
/// bytes say, and answering anyway is the thing sniffing exists not to do.
#[test]
fn no_two_bundled_formats_claim_the_same_file() {
    let with_magic: Vec<_> = bundled::all().iter().filter(|e| !e.signature.is_empty()).collect();
    for a in &with_magic {
        for b in &with_magic {
            if a.id >= b.id || !(fits(a.signature, b.signature) || fits(b.signature, a.signature)) {
                continue;
            }
            assert!(
                !a.sniffs && !b.sniffs,
                "{} and {} claim the same bytes and at least one of them sniffs",
                a.id,
                b.id
            );
        }
    }
    // And the ones that do sniff answer for themselves and nobody else.
    for entry in bundled::all() {
        if !entry.sniffs {
            continue;
        }
        let mut head = vec![0u8; 0x40];
        for (at, bytes) in entry.signature {
            head[*at as usize..*at as usize + bytes.len()].copy_from_slice(bytes);
        }
        assert_eq!(bundled::sniff(&head), Some(entry.name), "{} does not answer for itself", entry.id);
    }
}

/// A format made of itself: five of the bundled files hold another whole one
/// of the format inside a type of it, written as the file's own `meta/id`.
/// That name used to reach nothing, which cost each of them the field the rest
/// of the file hangs off.
#[test]
fn a_format_that_holds_another_one_of_itself_finds_its_own_root() {
    const RECURSIVE: &[&str] =
        &["asn1_der", "bson", "msgpack", "packet_ppi", "php_serialized_value"];
    for id in RECURSIVE {
        let text = std::fs::read_to_string(ksy_path(id)).expect("a bundled .ksy");
        let converted = qubero_core::ksy::convert(&text, &bundled::BundledImports)
            .unwrap_or_else(|e| panic!("{id} does not convert: {e}"));
        for gap in &converted.report.gaps {
            assert!(
                !gap.reason.contains("no type named"),
                "{id} {}: {}",
                gap.path,
                gap.reason
            );
        }
    }
}

/// Where a bundled `.ksy` sits, by its id. The directory mirrors the Kaitai
/// library's own, so the id alone does not say the path.
fn ksy_path(id: &str) -> PathBuf {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("formats-ksy");
    let mut found = Vec::new();
    walk_ksy(&dir, &mut found);
    found
        .into_iter()
        .find(|p| p.file_stem().map(|s| s == id).unwrap_or(false))
        .unwrap_or_else(|| panic!("no {id}.ksy under formats-ksy"))
}

fn walk_ksy(dir: &PathBuf, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk_ksy(&path, out);
        } else if path.extension().map(|e| e == "ksy").unwrap_or(false) {
            out.push(path);
        }
    }
}

/// A `.ksy` a reader pastes in can say `imports: [/common/vlq_base128_le]` and
/// find the shipped copy, which is what makes the bundled `common/` worth
/// having beyond the formats that use it here.
#[test]
fn a_pasted_ksy_can_import_from_the_bundled_collection() {
    let text = "meta:\n  id: borrows_a_vlq\n  imports:\n    - /common/vlq_base128_le\nseq:\n  - id: n\n    type: vlq_base128_le\n";
    let converted = qubero_core::ksy::convert(text, &bundled::BundledImports).expect("converts");
    assert!(converted.report.gaps.is_empty(), "gaps: {:?}", converted.report.gaps);
}

// ----- real files -----
//
// The sample collection was put together for the formats Qubero already reads,
// so most bundled Kaitai formats have nothing in it. RIFF is the exception and
// there are twenty-five of them, every one a real file written by a real
// encoder. `SAMPLES` below is the whole of what the collection can test; the
// formats it cannot are named in the skip message rather than left unsaid.

/// `(template, folder, file)` for every bundled format the sample collection
/// has a real file of.
const SAMPLES: &[(&str, &str, &str)] = &[
    ("ksy:riff", "wav", "pcm-s16le-stereo-44100.wav"),
    ("ksy:riff", "wav", "ieee-float32-stereo-48000.wav"),
    ("ksy:riff", "wav", "wave-extensible-pcm-5.1-48000.wav"),
    ("ksy:riff", "wav", "multiple-data-chunks-pcm16.wav"),
    ("ksy:riff", "wav", "broadcast-pcm16-bext-peak.wav"),
    ("ksy:riff", "wav", "ms-adpcm-stereo-22050.wav"),
];

/// Bundled formats worth a real file, that the collection has none of. Printed
/// by the test so the gap is visible rather than implied by a short list.
const NO_SAMPLE: &[&str] = &[
    "avi", "dex", "dicom", "ds_store", "edid", "ext2", "gpt_partition_table", "icc_4",
    "java_class", "mbr_partition_table", "mcap", "minecraft_nbt", "openpgp_message", "pcap",
    "python_pyc_27", "regf", "shapefile_main", "ssh_public_key", "ttf", "vfat",
    "windows_minidump",
];

fn sample(folder: &str, name: &str) -> Option<PathBuf> {
    let mut roots: Vec<PathBuf> = Vec::new();
    if let Ok(set) = std::env::var("QUBERO_SAMPLES") {
        roots.extend(set.split(';').filter(|s| !s.is_empty()).map(PathBuf::from));
    }
    roots.push(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../qubero-samples"));
    roots.push(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../qubero-samples"));
    roots.into_iter().map(|r| r.join(folder).join(name)).find(|p| p.exists())
}

#[test]
fn real_files_read_with_the_bundled_template() {
    let mut read = 0;
    for (template, folder, name) in SAMPLES {
        let Some(path) = sample(folder, name) else { continue };
        let bytes = std::fs::read(&path).unwrap();
        let len = bytes.len();
        let doc = Document::new(MemSource(bytes));
        let t = qubero_core::formats::template(template)
            .unwrap_or_else(|| panic!("{template} is not a template"));
        let mut ev = Evaluator::new(t);
        let root = ev.node(&doc, &[]).unwrap_or_else(|e| panic!("{name} has no root: {e:?}"));
        assert!(root.child_count > 0, "{name} read as {template} has no fields");
        for i in 0..root.child_count {
            let field = ev
                .node(&doc, &[i as usize])
                .unwrap_or_else(|e| panic!("{name} field {i} as {template}: {e:?}"));
            assert!(
                field.offset_bits + field.size_bits <= len as u64 * 8,
                "{name} field {} runs past the end",
                field.name
            );
        }
        read += 1;
    }
    if read == 0 {
        eprintln!("skipped: no sample collection (set QUBERO_SAMPLES)");
        return;
    }
    assert_eq!(read, SAMPLES.len(), "some sample files are missing");
    eprintln!(
        "read {read} real files with bundled templates. No file in the collection for: {}",
        NO_SAMPLE.join(", ")
    );
}

/// The whole point of reading a WAVE with the Kaitai RIFF description: it is
/// chunks, and their ids are the four letters the file writes.
#[test]
fn a_real_wave_reads_as_riff_chunks() {
    let Some(path) = sample("wav", "pcm-s16le-stereo-44100.wav") else {
        eprintln!("skipped: no sample collection (set QUBERO_SAMPLES)");
        return;
    };
    let doc = Document::new(MemSource(std::fs::read(&path).unwrap()));
    let mut ev = Evaluator::new(qubero_core::formats::template("ksy:riff").unwrap());
    let root = ev.node(&doc, &[]).unwrap();
    assert!(root.child_count >= 1, "a RIFF file is at least one chunk");
    let chunk = ev.node(&doc, &[0]).unwrap();
    assert_eq!(chunk.offset_bits, 0);
    assert!(chunk.size_bits > 0);
}

/// The same derivation `tools/ksy_bundle.mjs` asks the `ksy_gaps` example for:
/// the root's leading `contents`, plus every further one the walk reaches
/// through fields whose width does not depend on the data.
fn derive(root: &Ty) -> Vec<(u64, Vec<u8>)> {
    let mut out = Vec::new();
    let Ty::Struct(def) = root else { return out };
    let mut at = 0u64;
    for field in &def.fields {
        if let Ty::Magic(bytes) = &field.ty {
            out.push((at / 8, bytes.clone()));
        } else if out.is_empty() {
            return out;
        }
        match fixed_bits(&field.ty) {
            Some(bits) if (at + bits) % 8 == 0 => at += bits,
            _ => break,
        }
    }
    out
}

/// Whether a file matching `a` would also match `b`.
fn fits(a: &[(u64, &[u8])], b: &[(u64, &[u8])]) -> bool {
    b.iter().all(|(at, bytes)| {
        a.iter().any(|(a_at, a_bytes)| {
            *a_at <= *at
                && a_at + a_bytes.len() as u64 >= at + bytes.len() as u64
                && &a_bytes[(at - a_at) as usize..(at - a_at) as usize + bytes.len()] == *bytes
        })
    })
}
