//! Which tables the TSV files beside this hold, generated by
//! `node tools/bufrtables.mjs`. Do not edit.
//!
//! The current version is the WMO's BUFR4 release v46, under its MIT
//! licence. The older versions' differences are from ecCodes at commit
//! `9ad744c51deb09c831ca7750919093ad19fae5ad`, under the Apache License 2.0.

/// The version `element.tsv`, `sequence.tsv` and `operator.tsv` are.
pub const LATEST: u32 = 46;

/// The versions whose differences from it `older.tsv` holds.
pub const OLDER: &[u32] = &[13, 15];

pub const ELEMENTS: &str = include_str!("element.tsv");
pub const SEQUENCES: &str = include_str!("sequence.tsv");
pub const OPERATORS: &str = include_str!("operator.tsv");
pub const OLDER_TSV: &str = include_str!("older.tsv");
