//! The WMO's BUFR tables: what each descriptor is, how wide, and what a
//! sequence stands for.
//!
//! A BUFR message names every value by a descriptor and says nothing else
//! about it. That 0-12-101 is an air temperature in kelvin, scaled by 100 and
//! sixteen bits wide is written in Table B, not in the file, and that 3-01-001
//! is a block number and then a station number is written in Table D. A reader
//! without the tables cannot find where one value ends and the next begins.
//!
//! The tables are versioned, and a message says which version it was written
//! against in section 1. They only grow: a new version adds descriptors and
//! very rarely changes one, and when it does the change is what makes a message
//! read wrong against the wrong version. Class 14's radiation values went from
//! twelve bits to seventeen between versions 13 and 14, for instance. So what
//! is bundled is the current version in full and, for each older version the
//! sample files use, only the entries it says differently.
//!
//! The files beside this are generated by `node tools/bufrtables.mjs`, which
//! says where each part comes from; `generated.rs` records the versions. They
//! are parsed the first time a table is asked for and kept.
//!
//! A version that is not bundled is read with the nearest newer one that is,
//! and the current one past the end. That is the choice ecCodes makes for the
//! versions it only has a link for. Newer rather than older because a newer
//! table knows every descriptor an older message could name; a width changed
//! in between is a risk either way, and the reading says which version it used
//! so that a value that comes out wrong can be traced to it.

use std::collections::HashMap;
use std::sync::OnceLock;

mod generated;

pub use generated::LATEST;

/// A descriptor as the number the tables and every other reader write it as:
/// F, then X in two digits, then Y in three. 0-12-101 is `12101`.
pub fn code(f: u32, x: u32, y: u32) -> u32 {
    f * 100_000 + x * 1000 + y
}

/// What kind of value an element is, which decides whether the operators that
/// change widths and scales apply to it. They do not apply to text, or to a
/// code or flag table, whose numbers are names rather than measurements.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    Numeric,
    CodeTable,
    FlagTable,
    Text,
}

/// One entry of Table B.
#[derive(Debug, Clone, PartialEq)]
pub struct Element {
    pub name: &'static str,
    pub unit: &'static str,
    pub scale: i32,
    pub reference: i64,
    pub width: u32,
}

impl Element {
    pub fn kind(&self) -> Kind {
        kind_of(self.unit)
    }
}

/// What kind of value a Table B unit says an element is. Both copies of the
/// tables write words around a code table's unit, `Common Code table C-1`, so
/// it is looked for rather than matched.
pub fn kind_of(unit: &str) -> Kind {
    let u = unit.to_ascii_lowercase();
    if u.contains("code table") {
        Kind::CodeTable
    } else if u.contains("flag table") {
        Kind::FlagTable
    } else if u == "ccitt ia5" {
        Kind::Text
    } else {
        Kind::Numeric
    }
}

/// One entry of Table D: its title, which some sequences do not have, and the
/// descriptors it stands for, in order, as [`code`]s.
#[derive(Debug, Clone, PartialEq)]
pub struct Sequence {
    pub title: &'static str,
    pub members: Vec<u32>,
}

/// Tables B and D as one version has them.
#[derive(Debug)]
pub struct Tables {
    /// The version these are.
    pub version: u32,
    pub elements: HashMap<u32, Element>,
    pub sequences: HashMap<u32, Sequence>,
}

impl Tables {
    pub fn element(&self, code: u32) -> Option<&Element> {
        self.elements.get(&code)
    }

    pub fn sequence(&self, code: u32) -> Option<&Sequence> {
        self.sequences.get(&code)
    }
}

/// Every version that is bundled, oldest first, the current one last.
pub fn bundled() -> Vec<u32> {
    let mut v = generated::OLDER.to_vec();
    v.push(LATEST);
    v
}

/// The tables for a message written against `version`: that version if it is
/// bundled, otherwise the nearest newer one that is, otherwise the current
/// one. [`Tables::version`] says which it was.
pub fn for_version(version: u32) -> &'static Tables {
    static ALL: OnceLock<Vec<Tables>> = OnceLock::new();
    let all = ALL.get_or_init(|| {
        let latest = parse_latest();
        let mut out: Vec<Tables> = generated::OLDER.iter().map(|v| older(&latest, *v)).collect();
        out.push(latest);
        out
    });
    all.iter().find(|t| t.version >= version).unwrap_or_else(|| all.last().expect("the current version"))
}

/// The current version.
pub fn latest() -> &'static Tables {
    for_version(LATEST)
}

/// Table C's name for an operator descriptor, by its [`code`]. The table names
/// most operators once for every Y, as `201YYY`, and a few by their exact
/// value, as `223255` for the marker that differs from `223000`.
pub fn operator_name(code: u32) -> Option<&'static str> {
    static OPS: OnceLock<Vec<(&'static str, &'static str)>> = OnceLock::new();
    let ops = OPS.get_or_init(|| rows(generated::OPERATORS).filter_map(|r| Some((*r.first()?, *r.get(1)?))).collect());
    let exact = format!("{code:06}");
    let pattern = format!("{:03}YYY", code / 1000);
    ops.iter().find(|(c, _)| *c == exact).or_else(|| ops.iter().find(|(c, _)| *c == pattern)).map(|(_, n)| *n)
}

/// Table A: what kind of data a message holds, by the number section 1 gives.
/// The table's ranges of reserved numbers are left out, since a range is not a
/// value a message can hold and a reserved number is better shown as itself.
pub fn categories() -> Vec<(i128, &'static str)> {
    rows(generated::CATEGORIES).filter_map(|r| Some((r.first()?.parse().ok()?, *r.get(1)?))).collect()
}

/// The rows of one of the files, header left out, fields split on tabs.
fn rows(tsv: &'static str) -> impl Iterator<Item = Vec<&'static str>> {
    tsv.lines().skip(1).filter(|l| !l.is_empty()).map(|l| l.split('\t').collect())
}

fn parse_latest() -> Tables {
    let mut elements = HashMap::new();
    for r in rows(generated::ELEMENTS) {
        if let [c, scale, reference, width, unit, name] = r[..] {
            if let (Ok(c), Some(e)) = (c.parse::<u32>(), element(scale, reference, width, unit, name)) {
                elements.insert(c, e);
            }
        }
    }
    let mut sequences = HashMap::new();
    for r in rows(generated::SEQUENCES) {
        if let [c, title, members] = r[..] {
            if let Ok(c) = c.parse::<u32>() {
                sequences.insert(c, Sequence { title, members: members.split(' ').filter_map(|m| m.parse().ok()).collect() });
            }
        }
    }
    Tables { version: LATEST, elements, sequences }
}

fn element(scale: &str, reference: &str, width: &str, unit: &'static str, name: &'static str) -> Option<Element> {
    Some(Element { name, unit, scale: scale.parse().ok()?, reference: reference.parse().ok()?, width: width.parse().ok()? })
}

/// An older version: the current tables with what that version says
/// differently put back.
fn older(latest: &Tables, version: u32) -> Tables {
    let mut elements = latest.elements.clone();
    let mut sequences = latest.sequences.clone();
    let want = version.to_string();
    for r in rows(generated::OLDER_TSV) {
        let [v, table, c, scale, reference, width, unit, name, members] = r[..] else { continue };
        let Ok(c) = c.parse::<u32>() else { continue };
        if v != want {
            continue;
        }
        match table {
            "B" => {
                // No name in the file is a name the current table still has.
                let name = if name.is_empty() { latest.element(c).map_or("", |e| e.name) } else { name };
                if let Some(e) = element(scale, reference, width, unit, name) {
                    elements.insert(c, e);
                }
            }
            "D" => {
                let title = latest.sequence(c).map_or("", |s| s.title);
                sequences.insert(c, Sequence { title, members: members.split(' ').filter_map(|m| m.parse().ok()).collect() });
            }
            _ => {}
        }
    }
    Tables { version, elements, sequences }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_current_tables_know_an_air_temperature_and_a_station() {
        let t = latest();
        assert_eq!(t.version, LATEST);
        let e = t.element(12101).expect("0-12-101");
        assert_eq!((e.unit, e.scale, e.reference, e.width), ("K", 2, 0, 16));
        assert_eq!(e.name, "Temperature/air temperature");
        assert_eq!(t.element(1015).map(Element::kind), Some(Kind::Text));
        assert_eq!(t.element(31031).map(Element::kind), Some(Kind::FlagTable));
        assert_eq!(t.element(1033).map(Element::kind), Some(Kind::CodeTable));
        let s = t.sequence(301001).expect("3-01-001");
        assert_eq!(s.members, vec![1001, 1002]);
        assert_eq!(s.title, "WMO block and station numbers");
    }

    #[test]
    fn an_older_version_puts_back_what_it_said_differently() {
        // Class 14's radiation values were twelve bits wide in version 13 and
        // are seventeen now, with a different reference to match.
        let old = for_version(13);
        assert_eq!(old.version, 13);
        let e = old.element(14001).expect("0-14-001 in version 13");
        assert_eq!((e.width, e.reference), (12, -2048));
        let now = latest().element(14001).expect("0-14-001 now");
        assert_eq!((now.width, now.reference), (17, -65536));
        // And an entry that did not change is the current one, name and all.
        assert_eq!(old.element(12101), latest().element(12101));
    }

    #[test]
    fn a_version_that_is_not_bundled_reads_with_the_nearest_newer_one() {
        assert_eq!(for_version(11).version, 13);
        assert_eq!(for_version(14).version, 15);
        assert_eq!(for_version(16).version, LATEST);
        assert_eq!(for_version(LATEST + 10).version, LATEST);
    }

    #[test]
    fn operators_are_named_by_their_exact_value_before_their_pattern() {
        assert_eq!(operator_name(201130), Some("Change data width"));
        assert_eq!(operator_name(223000), Some("Substituted values operator"));
        assert_eq!(operator_name(223255), Some("Substituted values marker operator"));
        assert_eq!(operator_name(299000), None);
    }
}
