//! The Kaitai Struct format descriptions shipped inside Qubero.
//!
//! Every `.ksy` under `crates/core/formats-ksy` is a verbatim copy of a file
//! from the Kaitai Struct format library, compiled in with `include_str!` and
//! converted on demand. A bundled format is opened by a name like `ksy:png`,
//! and once converted it is a [`Template`](crate::template::Template) like any
//! other: nothing about it is Kaitai at run time.
//!
//! Which files are here, and why each one is, is
//! `crates/core/formats-ksy/README.md`. The short version: the licence has to
//! be one a redistributor can meet, and the conversion has to reach the bytes
//! a reader opens the file for. A format whose gaps are in a rare instance
//! ships with the gaps showing in the panel; one whose gaps are on the path
//! through the file does not ship at all.
//!
//! The table below is generated. `node tools/ksy_bundle.mjs` rewrites it and
//! the README from the directory, so adding a format is: copy the `.ksy` in,
//! run the script, run the tests.

use super::imports::Imports;
use super::lower::{convert, Converted};
use super::yaml::KsyError;

/// One shipped `.ksy`.
pub struct Bundled {
	/// `meta/id`, which is also what `ksy:<id>` opens.
	pub id: &'static str,
	/// The id with [`PREFIX`] on the front, which is the name a caller opens
	/// this by and the name [`sniff`] answers with. Written out rather than
	/// joined, because a sniffer answers with a `&'static str`.
	pub name: &'static str,
	/// The directory it sits in, which is the Kaitai library's own grouping:
	/// `image`, `network`, `common` and so on.
	pub category: &'static str,
	/// `meta/title`, empty for the files that carry none. Nothing invents one:
	/// a format with no title is shown by its id.
	pub title: &'static str,
	/// `meta/license`, as an SPDX identifier.
	pub licence: &'static str,
	/// Where this file came from, relative to the root of the Kaitai Struct
	/// format library. Also what an import naming a path resolves against.
	pub source: &'static str,
	/// The file, byte for byte.
	pub text: &'static str,
	/// Whether a reader may open a file as this. False for a file that is here
	/// only to be imported by another, and for a root type that takes
	/// parameters, which has no meaning without arguments nobody can supply.
	pub offered: bool,
	/// What a file of this format opens with, as `(offset, bytes)` pairs: the
	/// `contents` the format reads first, found through nested types, and
	/// every further `contents` reachable through fields of a fixed width.
	/// Derived by [`signature`](super::signature). See [`sniff`].
	pub signature: &'static [(u64, &'static [u8])],
	/// Whether [`sniff`] offers this format for a dropped file. False for a
	/// format with no leading magic, and for one whose magic another bundled
	/// format also claims.
	pub sniffs: bool,
	/// `meta/file-extension`, lower case and without the dot. What tells
	/// apart two formats whose bytes are the same: see [`sniff_named`].
	pub extensions: &'static [&'static str],
}

/// The name a bundled format is opened by. `ksy:` and the `meta/id`.
pub const PREFIX: &str = "ksy:";

/// The ids a reader may open a file as, in the order the table lists them.
/// Files that are here only to be imported are not among them.
pub fn names() -> Vec<&'static str> {
	BUNDLED.iter().filter(|b| b.offered).map(|b| b.id).collect()
}

/// The whole shipped collection, imports and all.
pub fn all() -> &'static [Bundled] {
	BUNDLED
}

/// One entry by its `meta/id`, whether or not it is offered.
pub fn find(id: &str) -> Option<&'static Bundled> {
	BUNDLED.iter().find(|b| b.id == id)
}

/// Convert a bundled format, imports resolved against the rest of the
/// collection. `None` for an id nothing here has.
///
/// The conversion happens now rather than at build time: the IR is Rust and
/// never serialised, so there is nothing to bake. It is a few milliseconds for
/// the largest of them, paid when a reader picks the format.
///
/// The [`Report`](super::Report) comes back with the template because it is
/// half the answer: a bundled format may have gaps, and the panel shows them.
pub fn template(id: &str) -> Option<Result<Converted, KsyError>> {
	let entry = find(id)?;
	Some(convert(entry.text, &BundledImports))
}

/// Resolve a `meta/imports` name against the bundled collection.
///
/// The wasm layer hands this to a `.ksy` the reader pasted in, so a file of
/// their own that says `imports: [/common/vlq_base128_le]` finds the same text
/// the shipped formats do.
pub struct BundledImports;

impl Imports for BundledImports {
	fn load(&self, name: &str) -> Option<String> {
		let want = name.trim_start_matches('/');
		let by_path = BUNDLED.iter().find(|b| b.source.trim_end_matches(".ksy") == want);
		let base = want.rsplit('/').next().unwrap_or(want);
		by_path.or_else(|| BUNDLED.iter().find(|b| b.id == base)).map(|b| b.text.to_string())
	}
}

/// Which bundled format, if any, claims a file that opens with these bytes,
/// as the `ksy:` name it is opened by.
///
/// Only what a format says out loud counts: the first thing it reads has to be
/// a `contents` at offset 0, nested types looked through, and the pattern is
/// that magic plus every further magic reachable through fields of a fixed
/// width. A format whose magic another bundled format shares claims nothing
/// here, because picking either would be a guess; [`sniff_named`] is where the
/// file's extension gets to settle that.
///
/// This is asked after every built-in probe, so a builtin's answer always
/// wins: see `formats::recognise::PROBES`.
pub fn sniff(head: &[u8]) -> Option<&'static str> {
	BUNDLED
		.iter()
		.find(|b| b.sniffs && matches(b.signature, head))
		.map(|b| b.name)
}

/// [`sniff`], and then, for a file whose bytes fit two bundled formats that
/// share a magic, the one whose `meta/file-extension` is the file's own.
///
/// The bytes still have the first word: a format only comes into it when its
/// whole signature fits the file, and the extension only chooses among those.
/// ESRI's `.shp` and `.shx` are the case in point: the same file code and the
/// same hundred-byte header, told apart by nothing but their names. `ext` is
/// the extension without the dot; case does not matter. `None` when the
/// bytes fit no format, or when the extension picks none or several of the
/// ones they fit.
pub fn sniff_named(head: &[u8], ext: &str) -> Option<&'static str> {
	if let Some(name) = sniff(head) {
		return Some(name);
	}
	let mut fits = BUNDLED.iter().filter(|b| {
		b.offered
			&& enough(b.signature)
			&& matches(b.signature, head)
			&& b.extensions.iter().any(|e| e.eq_ignore_ascii_case(ext))
	});
	match (fits.next(), fits.next()) {
		(Some(b), None) => Some(b.name),
		_ => None,
	}
}

fn matches(signature: &[(u64, &[u8])], head: &[u8]) -> bool {
	!signature.is_empty()
		&& signature.iter().all(|(at, bytes)| {
			let at = *at as usize;
			head.get(at..at + bytes.len()) == Some(*bytes)
		})
}

/// The two-byte rule: a one-byte magic claims every file whose first byte
/// happens to match, which is a guess dressed as an answer.
fn enough(signature: &[(u64, &[u8])]) -> bool {
	signature.iter().map(|(_, b)| b.len()).sum::<usize>() >= 2
}

// BEGIN GENERATED by tools/ksy_bundle.mjs -- do not edit by hand
pub const BUNDLED: &[Bundled] = &[
	Bundled {
		id: "android_bootldr_asus",
		name: "ksy:android_bootldr_asus",
		category: "archive",
		title: "ASUS Fugu bootloader.img format (version 2 and later)",
		licence: "CC0-1.0",
		source: "archive/android_bootldr_asus.ksy",
		text: include_str!("../../formats-ksy/archive/android_bootldr_asus.ksy"),
		offered: true,
		signature: &[(0, &[0x42, 0x4f, 0x4f, 0x54, 0x4c, 0x44, 0x52, 0x21])],
		sniffs: false,
		extensions: &["img"],
	},
	Bundled {
		id: "android_bootldr_huawei",
		name: "ksy:android_bootldr_huawei",
		category: "archive",
		title: "Huawei Bootloader packed image format",
		licence: "CC0-1.0",
		source: "archive/android_bootldr_huawei.ksy",
		text: include_str!("../../formats-ksy/archive/android_bootldr_huawei.ksy"),
		offered: true,
		signature: &[(0, &[0x3c, 0xd6, 0x1a, 0xce])],
		sniffs: true,
		extensions: &["img"],
	},
	Bundled {
		id: "android_bootldr_qcom",
		name: "ksy:android_bootldr_qcom",
		category: "archive",
		title: "Qualcomm Snapdragon (MSM) bootloader.img format",
		licence: "CC0-1.0",
		source: "archive/android_bootldr_qcom.ksy",
		text: include_str!("../../formats-ksy/archive/android_bootldr_qcom.ksy"),
		offered: true,
		signature: &[(0, &[0x42, 0x4f, 0x4f, 0x54, 0x4c, 0x44, 0x52, 0x21])],
		sniffs: false,
		extensions: &["img"],
	},
	Bundled {
		id: "android_dto",
		name: "ksy:android_dto",
		category: "archive",
		title: "Android DTB/DTBO Partition",
		licence: "CC0-1.0",
		source: "archive/android_dto.ksy",
		text: include_str!("../../formats-ksy/archive/android_dto.ksy"),
		offered: true,
		signature: &[(0, &[0xd7, 0xb7, 0xab, 0x1e])],
		sniffs: true,
		extensions: &["img"],
	},
	Bundled {
		id: "android_img",
		name: "ksy:android_img",
		category: "archive",
		title: "Android Boot Image",
		licence: "CC0-1.0",
		source: "archive/android_img.ksy",
		text: include_str!("../../formats-ksy/archive/android_img.ksy"),
		offered: true,
		signature: &[(0, &[0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49, 0x44, 0x21])],
		sniffs: true,
		extensions: &["img"],
	},
	Bundled {
		id: "mozilla_mar",
		name: "ksy:mozilla_mar",
		category: "archive",
		title: "Mozilla ARchive",
		licence: "CC0-1.0",
		source: "archive/mozilla_mar.ksy",
		text: include_str!("../../formats-ksy/archive/mozilla_mar.ksy"),
		offered: true,
		signature: &[(0, &[0x4d, 0x41, 0x52, 0x31])],
		sniffs: true,
		extensions: &["mar"],
	},
	Bundled {
		id: "phar_without_stub",
		name: "ksy:phar_without_stub",
		category: "archive",
		title: "PHP phar archive (without stub)",
		licence: "CC0-1.0",
		source: "archive/phar_without_stub.ksy",
		text: include_str!("../../formats-ksy/archive/phar_without_stub.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["phar"],
	},
	Bundled {
		id: "zisofs",
		name: "ksy:zisofs",
		category: "archive",
		title: "zisofs",
		licence: "CC0-1.0",
		source: "archive/zisofs.ksy",
		text: include_str!("../../formats-ksy/archive/zisofs.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "bcd",
		name: "ksy:bcd",
		category: "common",
		title: "BCD (Binary Coded Decimals)",
		licence: "CC0-1.0",
		source: "common/bcd.ksy",
		text: include_str!("../../formats-ksy/common/bcd.ksy"),
		offered: false,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "bytes_with_io",
		name: "ksy:bytes_with_io",
		category: "common",
		title: "Byte array with an `_io` member",
		licence: "MIT",
		source: "common/bytes_with_io.ksy",
		text: include_str!("../../formats-ksy/common/bytes_with_io.ksy"),
		offered: false,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "dos_datetime",
		name: "ksy:dos_datetime",
		category: "common",
		title: "MS-DOS datetime",
		licence: "CC0-1.0",
		source: "common/dos_datetime.ksy",
		text: include_str!("../../formats-ksy/common/dos_datetime.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "riff",
		name: "ksy:riff",
		category: "common",
		title: "Resource Interchange File Format (RIFF)",
		licence: "CC0-1.0",
		source: "common/riff.ksy",
		text: include_str!("../../formats-ksy/common/riff.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "utf8_string",
		name: "ksy:utf8_string",
		category: "common",
		title: "UTF-8-encoded string",
		licence: "CC0-1.0",
		source: "common/utf8_string.ksy",
		text: include_str!("../../formats-ksy/common/utf8_string.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["txt"],
	},
	Bundled {
		id: "vlq_base128_be",
		name: "ksy:vlq_base128_be",
		category: "common",
		title: "Variable length quantity, unsigned integer, base128, big-endian",
		licence: "CC0-1.0",
		source: "common/vlq_base128_be.ksy",
		text: include_str!("../../formats-ksy/common/vlq_base128_be.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "vlq_base128_le",
		name: "ksy:vlq_base128_le",
		category: "common",
		title: "Variable length quantity, unsigned/signed integer, base128, little-endian",
		licence: "CC0-1.0",
		source: "common/vlq_base128_le.ksy",
		text: include_str!("../../formats-ksy/common/vlq_base128_le.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "tsm",
		name: "ksy:tsm",
		category: "database",
		title: "InfluxDB TSM file",
		licence: "MIT",
		source: "database/tsm.ksy",
		text: include_str!("../../formats-ksy/database/tsm.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["tsm"],
	},
	Bundled {
		id: "android_nanoapp_header",
		name: "ksy:android_nanoapp_header",
		category: "executable",
		title: "Android nanoapp header",
		licence: "Apache-2.0",
		source: "executable/android_nanoapp_header.ksy",
		text: include_str!("../../formats-ksy/executable/android_nanoapp_header.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["napp_header"],
	},
	Bundled {
		id: "dex",
		name: "ksy:dex",
		category: "executable",
		title: "Android Dalvik VM executable (dex)",
		licence: "Apache-2.0",
		source: "executable/dex.ksy",
		text: include_str!("../../formats-ksy/executable/dex.ksy"),
		offered: true,
		signature: &[(0, &[0x64, 0x65, 0x78, 0x0a])],
		sniffs: true,
		extensions: &["dex"],
	},
	Bundled {
		id: "java_class",
		name: "ksy:java_class",
		category: "executable",
		title: "",
		licence: "CC0-1.0",
		source: "executable/java_class.ksy",
		text: include_str!("../../formats-ksy/executable/java_class.ksy"),
		offered: true,
		signature: &[(0, &[0xca, 0xfe, 0xba, 0xbe])],
		sniffs: true,
		extensions: &["class"],
	},
	Bundled {
		id: "python_pyc_27",
		name: "ksy:python_pyc_27",
		category: "executable",
		title: "",
		licence: "CC0-1.0",
		source: "executable/python_pyc_27.ksy",
		text: include_str!("../../formats-ksy/executable/python_pyc_27.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["pyc"],
	},
	Bundled {
		id: "uefi_te",
		name: "ksy:uefi_te",
		category: "executable",
		title: "TE (Terse Executable) file",
		licence: "CC0-1.0",
		source: "executable/uefi_te.ksy",
		text: include_str!("../../formats-ksy/executable/uefi_te.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["efi", "te"],
	},
	Bundled {
		id: "amlogic_emmc_partitions",
		name: "ksy:amlogic_emmc_partitions",
		category: "filesystem",
		title: "Amlogic proprietary eMMC partition table",
		licence: "CC0-1.0",
		source: "filesystem/amlogic_emmc_partitions.ksy",
		text: include_str!("../../formats-ksy/filesystem/amlogic_emmc_partitions.ksy"),
		offered: true,
		signature: &[(0, &[0x4d, 0x50, 0x54, 0x00])],
		sniffs: true,
		extensions: &[],
	},
	Bundled {
		id: "android_super",
		name: "ksy:android_super",
		category: "filesystem",
		title: "Android Dynamic Partitions metadata",
		licence: "CC0-1.0",
		source: "filesystem/android_super.ksy",
		text: include_str!("../../formats-ksy/filesystem/android_super.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["img"],
	},
	Bundled {
		id: "apm_partition_table",
		name: "ksy:apm_partition_table",
		category: "filesystem",
		title: "APM (Apple Partition Map) partition table",
		licence: "CC0-1.0",
		source: "filesystem/apm_partition_table.ksy",
		text: include_str!("../../formats-ksy/filesystem/apm_partition_table.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "btrfs_stream",
		name: "ksy:btrfs_stream",
		category: "filesystem",
		title: "",
		licence: "CC0-1.0",
		source: "filesystem/btrfs_stream.ksy",
		text: include_str!("../../formats-ksy/filesystem/btrfs_stream.ksy"),
		offered: true,
		signature: &[(0, &[0x62, 0x74, 0x72, 0x66, 0x73, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x00])],
		sniffs: true,
		extensions: &[],
	},
	Bundled {
		id: "cramfs",
		name: "ksy:cramfs",
		category: "filesystem",
		title: "",
		licence: "MIT",
		source: "filesystem/cramfs.ksy",
		text: include_str!("../../formats-ksy/filesystem/cramfs.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "ext2",
		name: "ksy:ext2",
		category: "filesystem",
		title: "ext2 filesystem",
		licence: "CC0-1.0",
		source: "filesystem/ext2.ksy",
		text: include_str!("../../formats-ksy/filesystem/ext2.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "gpt_partition_table",
		name: "ksy:gpt_partition_table",
		category: "filesystem",
		title: "GPT (GUID) partition table",
		licence: "CC0-1.0",
		source: "filesystem/gpt_partition_table.ksy",
		text: include_str!("../../formats-ksy/filesystem/gpt_partition_table.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "luks",
		name: "ksy:luks",
		category: "filesystem",
		title: "Linux Unified Key Setup",
		licence: "CC0-1.0",
		source: "filesystem/luks.ksy",
		text: include_str!("../../formats-ksy/filesystem/luks.ksy"),
		offered: true,
		signature: &[(0, &[0x4c, 0x55, 0x4b, 0x53, 0xba, 0xbe]), (6, &[0x00, 0x01])],
		sniffs: true,
		extensions: &[],
	},
	Bundled {
		id: "mbr_partition_table",
		name: "ksy:mbr_partition_table",
		category: "filesystem",
		title: "MBR (Master Boot Record) partition table",
		licence: "CC0-1.0",
		source: "filesystem/mbr_partition_table.ksy",
		text: include_str!("../../formats-ksy/filesystem/mbr_partition_table.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "tr_dos_image",
		name: "ksy:tr_dos_image",
		category: "filesystem",
		title: "TR-DOS flat-file disk image",
		licence: "CC0-1.0",
		source: "filesystem/tr_dos_image.ksy",
		text: include_str!("../../formats-ksy/filesystem/tr_dos_image.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["trd"],
	},
	Bundled {
		id: "vfat",
		name: "ksy:vfat",
		category: "filesystem",
		title: "",
		licence: "CC0-1.0",
		source: "filesystem/vfat.ksy",
		text: include_str!("../../formats-ksy/filesystem/vfat.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "vmware_vmdk",
		name: "ksy:vmware_vmdk",
		category: "filesystem",
		title: "VMWare Virtual Disk",
		licence: "CC0-1.0",
		source: "filesystem/vmware_vmdk.ksy",
		text: include_str!("../../formats-ksy/filesystem/vmware_vmdk.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["vmdk"],
	},
	Bundled {
		id: "uimage",
		name: "ksy:uimage",
		category: "firmware",
		title: "U-Boot Image wrapper",
		licence: "CC0-1.0",
		source: "firmware/uimage.ksy",
		text: include_str!("../../formats-ksy/firmware/uimage.ksy"),
		offered: true,
		signature: &[(0, &[0x27, 0x05, 0x19, 0x56])],
		sniffs: true,
		extensions: &[],
	},
	Bundled {
		id: "grub2_font",
		name: "ksy:grub2_font",
		category: "font",
		title: "GRUB 2 font",
		licence: "CC0-1.0",
		source: "font/grub2_font.ksy",
		text: include_str!("../../formats-ksy/font/grub2_font.ksy"),
		offered: true,
		signature: &[(0, &[0x46, 0x49, 0x4c, 0x45, 0x00, 0x00, 0x00, 0x04, 0x50, 0x46, 0x46, 0x32])],
		sniffs: true,
		extensions: &["pf2"],
	},
	Bundled {
		id: "pcf_font",
		name: "ksy:pcf_font",
		category: "font",
		title: "Portable Compiled Format (PCF) font",
		licence: "CC0-1.0",
		source: "font/pcf_font.ksy",
		text: include_str!("../../formats-ksy/font/pcf_font.ksy"),
		offered: true,
		signature: &[(0, &[0x01, 0x66, 0x63, 0x70])],
		sniffs: true,
		extensions: &["pcf"],
	},
	Bundled {
		id: "ttf",
		name: "ksy:ttf",
		category: "font",
		title: "TrueType Font File",
		licence: "MIT",
		source: "font/ttf.ksy",
		text: include_str!("../../formats-ksy/font/ttf.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["ttf"],
	},
	Bundled {
		id: "allegro_dat",
		name: "ksy:allegro_dat",
		category: "game",
		title: "Allegro data file",
		licence: "CC0-1.0",
		source: "game/allegro_dat.ksy",
		text: include_str!("../../formats-ksy/game/allegro_dat.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["dat"],
	},
	Bundled {
		id: "dune_2_pak",
		name: "ksy:dune_2_pak",
		category: "game",
		title: "",
		licence: "CC0-1.0",
		source: "game/dune_2_pak.ksy",
		text: include_str!("../../formats-ksy/game/dune_2_pak.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["pak"],
	},
	Bundled {
		id: "fallout2_dat",
		name: "ksy:fallout2_dat",
		category: "game",
		title: "",
		licence: "CC0-1.0",
		source: "game/fallout2_dat.ksy",
		text: include_str!("../../formats-ksy/game/fallout2_dat.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["dat"],
	},
	Bundled {
		id: "fallout_dat",
		name: "ksy:fallout_dat",
		category: "game",
		title: "",
		licence: "CC0-1.0",
		source: "game/fallout_dat.ksy",
		text: include_str!("../../formats-ksy/game/fallout_dat.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["dat"],
	},
	Bundled {
		id: "ftl_dat",
		name: "ksy:ftl_dat",
		category: "game",
		title: "",
		licence: "CC0-1.0",
		source: "game/ftl_dat.ksy",
		text: include_str!("../../formats-ksy/game/ftl_dat.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["dat"],
	},
	Bundled {
		id: "gran_turismo_vol",
		name: "ksy:gran_turismo_vol",
		category: "game",
		title: "Gran Turismo File System (GTFS)",
		licence: "CC0-1.0",
		source: "game/gran_turismo_vol.ksy",
		text: include_str!("../../formats-ksy/game/gran_turismo_vol.ksy"),
		offered: true,
		signature: &[(0, &[0x47, 0x54, 0x46, 0x53, 0x00, 0x00, 0x00, 0x00]), (12, &[0x00, 0x00, 0x00, 0x00])],
		sniffs: true,
		extensions: &["vol"],
	},
	Bundled {
		id: "heaps_pak",
		name: "ksy:heaps_pak",
		category: "game",
		title: "",
		licence: "MIT",
		source: "game/heaps_pak.ksy",
		text: include_str!("../../formats-ksy/game/heaps_pak.ksy"),
		offered: true,
		signature: &[(0, &[0x50, 0x41, 0x4b])],
		sniffs: true,
		extensions: &["pak"],
	},
	Bundled {
		id: "heroes_of_might_and_magic_agg",
		name: "ksy:heroes_of_might_and_magic_agg",
		category: "game",
		title: "",
		licence: "CC0-1.0",
		source: "game/heroes_of_might_and_magic_agg.ksy",
		text: include_str!("../../formats-ksy/game/heroes_of_might_and_magic_agg.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["agg"],
	},
	Bundled {
		id: "heroes_of_might_and_magic_bmp",
		name: "ksy:heroes_of_might_and_magic_bmp",
		category: "game",
		title: "",
		licence: "CC0-1.0",
		source: "game/heroes_of_might_and_magic_bmp.ksy",
		text: include_str!("../../formats-ksy/game/heroes_of_might_and_magic_bmp.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["bmp"],
	},
	Bundled {
		id: "minecraft_nbt",
		name: "ksy:minecraft_nbt",
		category: "game",
		title: "Minecraft NBT (Named Binary Tag)",
		licence: "CC0-1.0",
		source: "game/minecraft_nbt.ksy",
		text: include_str!("../../formats-ksy/game/minecraft_nbt.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["nbt", "dat", "schematic", "schem"],
	},
	Bundled {
		id: "saints_row_2_vpp_pc",
		name: "ksy:saints_row_2_vpp_pc",
		category: "game",
		title: "Saints Rows 2 game packages",
		licence: "MIT",
		source: "game/saints_row_2_vpp_pc.ksy",
		text: include_str!("../../formats-ksy/game/saints_row_2_vpp_pc.ksy"),
		offered: true,
		signature: &[(0, &[0xce, 0x0a, 0x89, 0x51, 0x04])],
		sniffs: true,
		extensions: &["vpp_pc"],
	},
	Bundled {
		id: "warcraft_2_pud",
		name: "ksy:warcraft_2_pud",
		category: "game",
		title: "Warcraft II map files",
		licence: "CC0-1.0",
		source: "game/warcraft_2_pud.ksy",
		text: include_str!("../../formats-ksy/game/warcraft_2_pud.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["pud"],
	},
	Bundled {
		id: "shapefile_index",
		name: "ksy:shapefile_index",
		category: "geospatial",
		title: "Shapefile index file",
		licence: "CC0-1.0",
		source: "geospatial/shapefile_index.ksy",
		text: include_str!("../../formats-ksy/geospatial/shapefile_index.ksy"),
		offered: true,
		signature: &[(0, &[0x00, 0x00, 0x27, 0x0a]), (4, &[0x00, 0x00, 0x00, 0x00]), (8, &[0x00, 0x00, 0x00, 0x00]), (12, &[0x00, 0x00, 0x00, 0x00]), (16, &[0x00, 0x00, 0x00, 0x00]), (20, &[0x00, 0x00, 0x00, 0x00]), (28, &[0xe8, 0x03, 0x00, 0x00])],
		sniffs: false,
		extensions: &["shx"],
	},
	Bundled {
		id: "shapefile_main",
		name: "ksy:shapefile_main",
		category: "geospatial",
		title: "Shapefile main file",
		licence: "CC0-1.0",
		source: "geospatial/shapefile_main.ksy",
		text: include_str!("../../formats-ksy/geospatial/shapefile_main.ksy"),
		offered: true,
		signature: &[(0, &[0x00, 0x00, 0x27, 0x0a]), (4, &[0x00, 0x00, 0x00, 0x00]), (8, &[0x00, 0x00, 0x00, 0x00]), (12, &[0x00, 0x00, 0x00, 0x00]), (16, &[0x00, 0x00, 0x00, 0x00]), (20, &[0x00, 0x00, 0x00, 0x00]), (28, &[0xe8, 0x03, 0x00, 0x00])],
		sniffs: false,
		extensions: &["shp"],
	},
	Bundled {
		id: "edid",
		name: "ksy:edid",
		category: "hardware",
		title: "EDID (VESA Enhanced Extended Display Identification Data)",
		licence: "CC0-1.0",
		source: "hardware/edid.ksy",
		text: include_str!("../../formats-ksy/hardware/edid.ksy"),
		offered: true,
		signature: &[(0, &[0x00, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x00])],
		sniffs: true,
		extensions: &[],
	},
	Bundled {
		id: "mifare_classic",
		name: "ksy:mifare_classic",
		category: "hardware",
		title: "Mifare Classic RFID tag dump",
		licence: "BSD-2-Clause",
		source: "hardware/mifare/mifare_classic.ksy",
		text: include_str!("../../formats-ksy/hardware/mifare/mifare_classic.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["mfd"],
	},
	Bundled {
		id: "dicom",
		name: "ksy:dicom",
		category: "image",
		title: "Digital Imaging and Communications in Medicine (DICOM) file format",
		licence: "MIT",
		source: "image/dicom.ksy",
		text: include_str!("../../formats-ksy/image/dicom.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["dcm"],
	},
	Bundled {
		id: "gimp_brush",
		name: "ksy:gimp_brush",
		category: "image",
		title: "GIMP brush file version 2",
		licence: "CC0-1.0",
		source: "image/gimp_brush.ksy",
		text: include_str!("../../formats-ksy/image/gimp_brush.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["gbr"],
	},
	Bundled {
		id: "icc_4",
		name: "ksy:icc_4",
		category: "image",
		title: "ICC profile, version 4",
		licence: "CC0-1.0",
		source: "image/icc_4.ksy",
		text: include_str!("../../formats-ksy/image/icc_4.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["icc", "icm"],
	},
	Bundled {
		id: "pcx",
		name: "ksy:pcx",
		category: "image",
		title: "",
		licence: "CC0-1.0",
		source: "image/pcx.ksy",
		text: include_str!("../../formats-ksy/image/pcx.ksy"),
		offered: false,
		signature: &[],
		sniffs: false,
		extensions: &["pcx"],
	},
	Bundled {
		id: "pcx_dcx",
		name: "ksy:pcx_dcx",
		category: "image",
		title: "",
		licence: "CC0-1.0",
		source: "image/pcx_dcx.ksy",
		text: include_str!("../../formats-ksy/image/pcx_dcx.ksy"),
		offered: true,
		signature: &[(0, &[0xb1, 0x68, 0xde, 0x3a])],
		sniffs: true,
		extensions: &["dcx"],
	},
	Bundled {
		id: "psx_tim",
		name: "ksy:psx_tim",
		category: "image",
		title: "",
		licence: "CC0-1.0",
		source: "image/psx_tim.ksy",
		text: include_str!("../../formats-ksy/image/psx_tim.ksy"),
		offered: true,
		signature: &[(0, &[0x10, 0x00, 0x00, 0x00])],
		sniffs: true,
		extensions: &["tim"],
	},
	Bundled {
		id: "wmf",
		name: "ksy:wmf",
		category: "image",
		title: "Windows Metafile (WMF) vector image",
		licence: "CC0-1.0",
		source: "image/wmf.ksy",
		text: include_str!("../../formats-ksy/image/wmf.ksy"),
		offered: true,
		signature: &[(0, &[0xd7, 0xcd, 0xc6, 0x9a]), (4, &[0x00, 0x00]), (16, &[0x00, 0x00, 0x00, 0x00])],
		sniffs: true,
		extensions: &["wmf"],
	},
	Bundled {
		id: "xwd",
		name: "ksy:xwd",
		category: "image",
		title: "xwd (X Window Dump) bitmap image",
		licence: "CC0-1.0",
		source: "image/xwd.ksy",
		text: include_str!("../../formats-ksy/image/xwd.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["xwd"],
	},
	Bundled {
		id: "hashcat_restore",
		name: "ksy:hashcat_restore",
		category: "log",
		title: "Hashcat Restore file",
		licence: "CC0-1.0",
		source: "log/hashcat_restore.ksy",
		text: include_str!("../../formats-ksy/log/hashcat_restore.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["restore"],
	},
	Bundled {
		id: "mcap",
		name: "ksy:mcap",
		category: "log",
		title: "MCAP",
		licence: "Apache-2.0",
		source: "log/mcap.ksy",
		text: include_str!("../../formats-ksy/log/mcap.ksy"),
		offered: true,
		signature: &[(0, &[0x89, 0x4d, 0x43, 0x41, 0x50, 0x30, 0x0d, 0x0a])],
		sniffs: true,
		extensions: &["mcap"],
	},
	Bundled {
		id: "sudoers_ts",
		name: "ksy:sudoers_ts",
		category: "log",
		title: "Sudoers Time Stamp file",
		licence: "CC0-1.0",
		source: "log/sudoers_ts.ksy",
		text: include_str!("../../formats-ksy/log/sudoers_ts.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "windows_evt_log",
		name: "ksy:windows_evt_log",
		category: "log",
		title: "Windows Event Log (EVT)",
		licence: "CC0-1.0",
		source: "log/windows_evt_log.ksy",
		text: include_str!("../../formats-ksy/log/windows_evt_log.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["evt"],
	},
	Bundled {
		id: "compressed_resource",
		name: "ksy:compressed_resource",
		category: "macos",
		title: "Compressed Macintosh resource",
		licence: "MIT",
		source: "macos/compressed_resource.ksy",
		text: include_str!("../../formats-ksy/macos/compressed_resource.ksy"),
		offered: true,
		signature: &[(0, &[0xa8, 0x9f, 0x65, 0x72])],
		sniffs: true,
		extensions: &[],
	},
	Bundled {
		id: "ds_store",
		name: "ksy:ds_store",
		category: "macos",
		title: "macOS '.DS_Store' format",
		licence: "MIT",
		source: "macos/ds_store.ksy",
		text: include_str!("../../formats-ksy/macos/ds_store.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["ds_store"],
	},
	Bundled {
		id: "mac_os_resource_snd",
		name: "ksy:mac_os_resource_snd",
		category: "macos",
		title: "Classic MacOS Sound Resource",
		licence: "MIT",
		source: "macos/mac_os_resource_snd.ksy",
		text: include_str!("../../formats-ksy/macos/mac_os_resource_snd.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "dcmp_0",
		name: "ksy:dcmp_0",
		category: "macos",
		title: "Compressed Macintosh resource data, Apple `'dcmp' (0)` format",
		licence: "MIT",
		source: "macos/resource_compression/dcmp_0.ksy",
		text: include_str!("../../formats-ksy/macos/resource_compression/dcmp_0.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "dcmp_1",
		name: "ksy:dcmp_1",
		category: "macos",
		title: "Compressed Macintosh resource data, Apple `'dcmp' (1)` format",
		licence: "MIT",
		source: "macos/resource_compression/dcmp_1.ksy",
		text: include_str!("../../formats-ksy/macos/resource_compression/dcmp_1.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "dcmp_2",
		name: "ksy:dcmp_2",
		category: "macos",
		title: "Compressed Macintosh resource data, Apple `'dcmp' (2)` format",
		licence: "MIT",
		source: "macos/resource_compression/dcmp_2.ksy",
		text: include_str!("../../formats-ksy/macos/resource_compression/dcmp_2.ksy"),
		offered: false,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "dcmp_variable_length_integer",
		name: "ksy:dcmp_variable_length_integer",
		category: "macos",
		title: "Variable-length integer used in Apple `'dcmp' (0)` and `'dcmp' (1)` compressed resource formats",
		licence: "MIT",
		source: "macos/resource_compression/dcmp_variable_length_integer.ksy",
		text: include_str!("../../formats-ksy/macos/resource_compression/dcmp_variable_length_integer.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "resource_fork",
		name: "ksy:resource_fork",
		category: "macos",
		title: "Macintosh resource fork data",
		licence: "MIT",
		source: "macos/resource_fork.ksy",
		text: include_str!("../../formats-ksy/macos/resource_fork.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["rsrc", "dfont"],
	},
	Bundled {
		id: "avi",
		name: "ksy:avi",
		category: "media",
		title: "Microsoft AVI file",
		licence: "CC0-1.0",
		source: "media/avi.ksy",
		text: include_str!("../../formats-ksy/media/avi.ksy"),
		offered: true,
		signature: &[(0, &[0x52, 0x49, 0x46, 0x46]), (8, &[0x41, 0x56, 0x49, 0x20])],
		sniffs: true,
		extensions: &["avi"],
	},
	Bundled {
		id: "creative_voice_file",
		name: "ksy:creative_voice_file",
		category: "media",
		title: "Creative Voice File",
		licence: "CC0-1.0",
		source: "media/creative_voice_file.ksy",
		text: include_str!("../../formats-ksy/media/creative_voice_file.ksy"),
		offered: true,
		signature: &[(0, &[0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x76, 0x65, 0x20, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x20, 0x46, 0x69, 0x6c, 0x65, 0x1a])],
		sniffs: true,
		extensions: &["voc"],
	},
	Bundled {
		id: "genmidi_op2",
		name: "ksy:genmidi_op2",
		category: "media",
		title: "GENMIDI.OP2 OPL2 sound bank",
		licence: "CC0-1.0",
		source: "media/genmidi_op2.ksy",
		text: include_str!("../../formats-ksy/media/genmidi_op2.ksy"),
		offered: true,
		signature: &[(0, &[0x23, 0x4f, 0x50, 0x4c, 0x5f, 0x49, 0x49, 0x23])],
		sniffs: true,
		extensions: &["op2"],
	},
	Bundled {
		id: "magicavoxel_vox",
		name: "ksy:magicavoxel_vox",
		category: "media",
		title: "MagicaVoxel File",
		licence: "MIT",
		source: "media/magicavoxel_vox.ksy",
		text: include_str!("../../formats-ksy/media/magicavoxel_vox.ksy"),
		offered: true,
		signature: &[(0, &[0x56, 0x4f, 0x58, 0x20])],
		sniffs: true,
		extensions: &["vox"],
	},
	Bundled {
		id: "vp8_duck_ivf",
		name: "ksy:vp8_duck_ivf",
		category: "media",
		title: "Duck IVF (container format for VP8)",
		licence: "CC0-1.0",
		source: "media/vp8_duck_ivf.ksy",
		text: include_str!("../../formats-ksy/media/vp8_duck_ivf.ksy"),
		offered: true,
		signature: &[(0, &[0x44, 0x4b, 0x49, 0x46]), (8, &[0x56, 0x50, 0x38, 0x30])],
		sniffs: true,
		extensions: &["ivf"],
	},
	Bundled {
		id: "bitcoin_transaction",
		name: "ksy:bitcoin_transaction",
		category: "network",
		title: "Bitcoin Transaction",
		licence: "MIT",
		source: "network/bitcoin_transaction.ksy",
		text: include_str!("../../formats-ksy/network/bitcoin_transaction.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "dime_message",
		name: "ksy:dime_message",
		category: "network",
		title: "DIME (Direct Internet Message Encapsulation) Message",
		licence: "CC0-1.0",
		source: "network/dime_message.ksy",
		text: include_str!("../../formats-ksy/network/dime_message.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["dim", "dime"],
	},
	Bundled {
		id: "dns_packet",
		name: "ksy:dns_packet",
		category: "network",
		title: "DNS (Domain Name Service) packet",
		licence: "CC0-1.0",
		source: "network/dns_packet.ksy",
		text: include_str!("../../formats-ksy/network/dns_packet.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "ethernet_frame",
		name: "ksy:ethernet_frame",
		category: "network",
		title: "Ethernet frame (layer 2, IEEE 802.3)",
		licence: "CC0-1.0",
		source: "network/ethernet_frame.ksy",
		text: include_str!("../../formats-ksy/network/ethernet_frame.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "hccap",
		name: "ksy:hccap",
		category: "network",
		title: "Hashcat capture file (old version)",
		licence: "Unlicense",
		source: "network/hccap.ksy",
		text: include_str!("../../formats-ksy/network/hccap.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["hccap"],
	},
	Bundled {
		id: "hccapx",
		name: "ksy:hccapx",
		category: "network",
		title: "Hashcat capture file",
		licence: "Unlicense",
		source: "network/hccapx.ksy",
		text: include_str!("../../formats-ksy/network/hccapx.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["hccapx"],
	},
	Bundled {
		id: "icmp_packet",
		name: "ksy:icmp_packet",
		category: "network",
		title: "ICMP network packet",
		licence: "CC0-1.0",
		source: "network/icmp_packet.ksy",
		text: include_str!("../../formats-ksy/network/icmp_packet.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "ipv4_packet",
		name: "ksy:ipv4_packet",
		category: "network",
		title: "IPv4 network packet",
		licence: "CC0-1.0",
		source: "network/ipv4_packet.ksy",
		text: include_str!("../../formats-ksy/network/ipv4_packet.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "ipv6_packet",
		name: "ksy:ipv6_packet",
		category: "network",
		title: "IPv6 network packet",
		licence: "CC0-1.0",
		source: "network/ipv6_packet.ksy",
		text: include_str!("../../formats-ksy/network/ipv6_packet.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "microsoft_network_monitor_v2",
		name: "ksy:microsoft_network_monitor_v2",
		category: "network",
		title: "",
		licence: "CC0-1.0",
		source: "network/microsoft_network_monitor_v2.ksy",
		text: include_str!("../../formats-ksy/network/microsoft_network_monitor_v2.ksy"),
		offered: true,
		signature: &[(0, &[0x47, 0x4d, 0x42, 0x55])],
		sniffs: true,
		extensions: &["cap"],
	},
	Bundled {
		id: "packet_ppi",
		name: "ksy:packet_ppi",
		category: "network",
		title: "",
		licence: "CC0-1.0",
		source: "network/packet_ppi.ksy",
		text: include_str!("../../formats-ksy/network/packet_ppi.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "protocol_body",
		name: "ksy:protocol_body",
		category: "network",
		title: "",
		licence: "CC0-1.0",
		source: "network/protocol_body.ksy",
		text: include_str!("../../formats-ksy/network/protocol_body.ksy"),
		offered: false,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "rtp_packet",
		name: "ksy:rtp_packet",
		category: "network",
		title: "RTP (Real-time Transport Protocol)",
		licence: "Unlicense",
		source: "network/rtp_packet.ksy",
		text: include_str!("../../formats-ksy/network/rtp_packet.ksy"),
		offered: false,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "rtpdump",
		name: "ksy:rtpdump",
		category: "network",
		title: "Rtpdump (rtptools)",
		licence: "Unlicense",
		source: "network/rtpdump.ksy",
		text: include_str!("../../formats-ksy/network/rtpdump.ksy"),
		offered: true,
		signature: &[(0, &[0x23, 0x21, 0x72, 0x74, 0x70, 0x70, 0x6c, 0x61, 0x79, 0x31, 0x2e, 0x30]), (12, &[0x20])],
		sniffs: true,
		extensions: &["rtp", "rtpdump"],
	},
	Bundled {
		id: "tcp_segment",
		name: "ksy:tcp_segment",
		category: "network",
		title: "TCP (Transmission Control Protocol) segment",
		licence: "CC0-1.0",
		source: "network/tcp_segment.ksy",
		text: include_str!("../../formats-ksy/network/tcp_segment.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "tls_client_hello",
		name: "ksy:tls_client_hello",
		category: "network",
		title: "",
		licence: "MIT",
		source: "network/tls_client_hello.ksy",
		text: include_str!("../../formats-ksy/network/tls_client_hello.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "udp_datagram",
		name: "ksy:udp_datagram",
		category: "network",
		title: "UDP (User Datagram Protocol) datagram",
		licence: "CC0-1.0",
		source: "network/udp_datagram.ksy",
		text: include_str!("../../formats-ksy/network/udp_datagram.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "nt_mdt_pal",
		name: "ksy:nt_mdt_pal",
		category: "scientific",
		title: "NT-MDT palette format",
		licence: "Unlicense",
		source: "scientific/nt_mdt/nt_mdt_pal.ksy",
		text: include_str!("../../formats-ksy/scientific/nt_mdt/nt_mdt_pal.ksy"),
		offered: true,
		signature: &[(0, &[0x4e, 0x54, 0x2d, 0x4d, 0x44, 0x54, 0x20, 0x50, 0x61, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x20, 0x46, 0x69, 0x6c, 0x65, 0x20, 0x20, 0x31, 0x2e, 0x30, 0x30, 0x21])],
		sniffs: true,
		extensions: &["pal"],
	},
	Bundled {
		id: "avantes_roh60",
		name: "ksy:avantes_roh60",
		category: "scientific",
		title: "Avantes USB spectrometer ROH file 6.0",
		licence: "CC0-1.0",
		source: "scientific/spectroscopy/avantes_roh60.ksy",
		text: include_str!("../../formats-ksy/scientific/spectroscopy/avantes_roh60.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["roh"],
	},
	Bundled {
		id: "specpr",
		name: "ksy:specpr",
		category: "scientific",
		title: "SPECtrum Processing Routines Data Format 3/4/88",
		licence: "Unlicense",
		source: "scientific/spectroscopy/specpr.ksy",
		text: include_str!("../../formats-ksy/scientific/spectroscopy/specpr.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["spec"],
	},
	Bundled {
		id: "efivar_signature_list",
		name: "ksy:efivar_signature_list",
		category: "security",
		title: "UEFI Variable with Signature List",
		licence: "CC0-1.0",
		source: "security/efivar_signature_list.ksy",
		text: include_str!("../../formats-ksy/security/efivar_signature_list.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "openpgp_message",
		name: "ksy:openpgp_message",
		category: "security",
		title: "OpenPGP message",
		licence: "MIT",
		source: "security/openpgp_message.ksy",
		text: include_str!("../../formats-ksy/security/openpgp_message.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["gpg", "pub", "pgp"],
	},
	Bundled {
		id: "ssh_public_key",
		name: "ksy:ssh_public_key",
		category: "security",
		title: "SSH public key",
		licence: "CC0-1.0",
		source: "security/ssh_public_key.ksy",
		text: include_str!("../../formats-ksy/security/ssh_public_key.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "asn1_der",
		name: "ksy:asn1_der",
		category: "serialization",
		title: "ASN.1 DER (Abstract Syntax Notation One, Distinguished Encoding Rules)",
		licence: "CC0-1.0",
		source: "serialization/asn1/asn1_der.ksy",
		text: include_str!("../../formats-ksy/serialization/asn1/asn1_der.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["der"],
	},
	Bundled {
		id: "bson",
		name: "ksy:bson",
		category: "serialization",
		title: "",
		licence: "CC0-1.0",
		source: "serialization/bson.ksy",
		text: include_str!("../../formats-ksy/serialization/bson.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["bson"],
	},
	Bundled {
		id: "chrome_pak",
		name: "ksy:chrome_pak",
		category: "serialization",
		title: "Chrome PAK serialization format",
		licence: "CC0-1.0",
		source: "serialization/chrome_pak.ksy",
		text: include_str!("../../formats-ksy/serialization/chrome_pak.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &["pak"],
	},
	Bundled {
		id: "google_protobuf",
		name: "ksy:google_protobuf",
		category: "serialization",
		title: "Google Protocol Buffers (protobuf)",
		licence: "MIT",
		source: "serialization/google_protobuf.ksy",
		text: include_str!("../../formats-ksy/serialization/google_protobuf.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "msgpack",
		name: "ksy:msgpack",
		category: "serialization",
		title: "MessagePack (msgpack) serialization format",
		licence: "CC0-1.0",
		source: "serialization/msgpack.ksy",
		text: include_str!("../../formats-ksy/serialization/msgpack.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "php_serialized_value",
		name: "ksy:php_serialized_value",
		category: "serialization",
		title: "Serialized PHP value",
		licence: "CC0-1.0",
		source: "serialization/php_serialized_value.ksy",
		text: include_str!("../../formats-ksy/serialization/php_serialized_value.ksy"),
		offered: false,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "ruby_marshal",
		name: "ksy:ruby_marshal",
		category: "serialization",
		title: "",
		licence: "CC0-1.0",
		source: "serialization/ruby_marshal.ksy",
		text: include_str!("../../formats-ksy/serialization/ruby_marshal.ksy"),
		offered: true,
		signature: &[(0, &[0x04, 0x08])],
		sniffs: true,
		extensions: &[],
	},
	Bundled {
		id: "regf",
		name: "ksy:regf",
		category: "windows",
		title: "Windows registry database",
		licence: "CC0-1.0",
		source: "windows/regf.ksy",
		text: include_str!("../../formats-ksy/windows/regf.ksy"),
		offered: true,
		signature: &[(0, &[0x72, 0x65, 0x67, 0x66])],
		sniffs: true,
		extensions: &[],
	},
	Bundled {
		id: "windows_minidump",
		name: "ksy:windows_minidump",
		category: "windows",
		title: "Windows MiniDump",
		licence: "CC0-1.0",
		source: "windows/windows_minidump.ksy",
		text: include_str!("../../formats-ksy/windows/windows_minidump.ksy"),
		offered: true,
		signature: &[(0, &[0x4d, 0x44, 0x4d, 0x50]), (4, &[0x93, 0xa7])],
		sniffs: true,
		extensions: &["dmp", "mdmp"],
	},
	Bundled {
		id: "windows_shell_items",
		name: "ksy:windows_shell_items",
		category: "windows",
		title: "Windows Shell Items",
		licence: "CC0-1.0",
		source: "windows/windows_shell_items.ksy",
		text: include_str!("../../formats-ksy/windows/windows_shell_items.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
	Bundled {
		id: "windows_systemtime",
		name: "ksy:windows_systemtime",
		category: "windows",
		title: "Microsoft Windows SYSTEMTIME structure",
		licence: "CC0-1.0",
		source: "windows/windows_systemtime.ksy",
		text: include_str!("../../formats-ksy/windows/windows_systemtime.ksy"),
		offered: true,
		signature: &[],
		sniffs: false,
		extensions: &[],
	},
];
// END GENERATED

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn every_bundled_licence_is_one_we_may_redistribute() {
		// The list from HANDOVER-kaitai.md. A `.ksy` under anything else is
		// not copied into this repository at all, so this failing means a file
		// arrived without the check being run.
		const ALLOWED: &[&str] =
			&["CC0-1.0", "MIT", "Unlicense", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause"];
		for entry in BUNDLED {
			assert!(
				ALLOWED.contains(&entry.licence),
				"{} is {}, which is not a licence this ships under",
				entry.id,
				entry.licence
			);
		}
	}

	#[test]
	fn an_import_finds_the_file_by_path_or_by_name() {
		assert!(BundledImports.load("/common/vlq_base128_le").is_some());
		assert!(BundledImports.load("common/vlq_base128_le").is_some());
		assert!(BundledImports.load("vlq_base128_le").is_some());
		assert!(BundledImports.load("nothing_by_that_name").is_none());
	}
}
