"""Count hexpat constructs across the ImHex-Patterns corpus, to rank IR additions."""
import re, glob, sys

root = sys.argv[1] if len(sys.argv) > 1 else "/home/pengo/github/ImHex-Patterns"
files = sorted(glob.glob(root + "/patterns/**/*.hexpat", recursive=True))
texts = {}
for f in files:
    t = open(f, encoding="utf-8", errors="replace").read()
    texts[f] = re.sub(r"//.*|/\*.*?\*/", "", t, flags=re.S)


def count(name, pat, flags=re.M):
    n = sum(1 for t in texts.values() if re.search(pat, t, flags))
    occ = sum(len(re.findall(pat, t, flags)) for t in texts.values())
    print(f"{n:4d} files {occ:6d} occ  {name}")


print("== structure")
count("union", r"\bunion\s+\w+")
count("struct inheritance", r"\bstruct\s+\w+\s*:\s*\w+")
count("templates <auto>", r"\bstruct\s+\w+\s*<|<\s*auto\b")
count("pointer  T *x : u32", r"\*\s*\w+\s*:\s*(u8|u16|u32|u64|s8|s16|s32|s64)\b")
count("pointer_base attr", r"pointer_base")
count("unsized array x[]", r"\w+\s*\[\s*\]\s*[;@\[]")
count("[while(...)]", r"\[\s*while\s*\(")
count("while(!std::mem::eof", r"\[\s*while\s*\(\s*!\s*std::mem::eof")
count("while($ < ...)", r"\[\s*while\s*\(\s*\$\s*<")
count("while with parent./this.", r"\[\s*while\s*\([^\]]*(parent|this)\.")
count("placement @ at top level", r"^\s*[A-Za-z_][\w:<>]*\s+\w+\s*(\[[^\]]*\])?\s*@\s*")
count("@ $", r"@\s*\$")
count("@ addressof", r"@\s*addressof")
count("if in struct", r"^\s+if\s*\(")
count("else", r"\belse\b")
count("match (", r"\bmatch\s*\(")
count("padding[", r"\bpadding\s*\[")
count("bitfield", r"\bbitfield\s+\w+")
count("bitfield signed/bool/enum member", r"^\s*(signed|bool|unsigned)\s+\w+\s*:\s*\d|^\s*[A-Z]\w+\s+\w+\s*:\s*\d")
count("bitfield typed member uN x : n", r"^\s*(u8|u16|u32|u64)\s+\w+\s*:\s*\d+")
count("bitfield padding : n", r"^\s*padding\s*:\s*\d")
count("left_to_right/right_to_left", r"left_to_right|right_to_left|bitfield_order")
count("enum ranges ...", r"\.\.\.")
count("enum : type", r"\benum\s+\w+\s*:\s*\w+")
count("char x[N] string", r"\bchar\s+\w+\s*\[")
count("char x[] nul-terminated", r"\bchar\s+\w+\s*\[\s*\]")
count("char16", r"\bchar16\b")
count("str type field", r"^\s*str\s+\w+")
count("float16/double/float", r"\b(float16|double|float)\b")
count("u128/s128", r"\b[us]128\b")
count("bool", r"\bbool\s+\w+")
count("le/be prefix on field", r"\b(le|be)\s+(u8|u16|u32|u64|s8|s16|s32|s64|float|double|char16|\w+)\s+\w+")
count("#pragma endian", r"#pragma\s+endian")
count("#pragma magic", r"#pragma\s+magic")
count("set_endian call", r"std::core::set_endian")
count("using alias", r"\busing\s+\w+\s*=")
count("namespace", r"\bnamespace\s+\w+")
count("type::Magic<", r"type::Magic\s*<")
count("type::GUID", r"type::GUID")
count("type::time32_t/time64/FILETIME/DOS", r"type::(time32_t|time64_t|FILETIME|DOSTime|DOSDate)")
count("type::Size*", r"type::Size(32|16|64|8)?\b")
count("type::u?LEB128", r"type::[us]?LEB128")
count("type::Hex/RGBA/Nibbles/escape", r"type::(Hex|RGBA8|Nibbles|escape_bytes)")
print("== expressions")
count("bitwise | in expr", r"[^|]\|[^|=]")
count("bitwise ^", r"\^")
count("bitwise ~", r"~")
count("ternary ?:", r"\?[^?]*:")
count("sizeof(", r"\bsizeof\s*\(")
count("addressof(", r"\baddressof\s*\(")
count("parent.", r"\bparent\.")
count("parent.parent.", r"\bparent\.parent\.")
count("this.", r"\bthis\.")
count("$ read (not assign)", r"\$(?!\s*[+\-]?=)")
count("$ assign", r"\$\s*[+\-]?=")
count("std::mem::eof", r"std::mem::eof")
count("std::mem::size", r"std::mem::size\(")
count("std::mem::read_", r"std::mem::read_\w+")
count("std::mem sections", r"std::mem::(create_section|copy_section|section)")
count("array subscript in expr", r"\w\[\s*\w+\s*\]\s*[=.!<>+\-*/)]")
count("enum value in expr X::Y", r"\b[A-Z]\w*::[A-Za-z_]\w*\b")
count("string literal compare", r'==\s*"')
count("float literal", r"\b\d+\.\d+f?\b")
count("shift <<>>", r"<<|>>")
print("== attributes")
for a in ["name", "comment", "format", "format_read", "hidden", "inline", "color", "single_color", "transform", "sealed", "static", "no_unique_address", "hex::spec_name", "hex::visualize", "highlight_hidden", "pointer_base", "export", "fixed_size"]:
    count(f"[[{a}", r"\[\[\s*" + re.escape(a) + r"\b")
print("== imperative (gaps)")
count("fn", r"\bfn\s+\w+\s*\(")
count("while statement (not array)", r"^\s*while\s*\(")
count("for (", r"\bfor\s*\(")
count("local variable decl in struct", r"^\s*(u8|u16|u32|u64|s8|s16|s32|s64|str|bool|auto)\s+\w+\s*=")
count("in/out", r"^\s*(in|out)\s+\w")
count("try", r"\btry\s*\{")
count("std::format/print (display)", r"std::(format|print)\b")
count("std::assert/warning/error", r"std::(assert|assert_warn|warning|error)\b")
count("set_display_name", r"set_display_name")
count("std::core::member_count/array_index", r"std::core::(member_count|array_index)")
count("break/continue/return", r"\b(break|continue|return)\b")
