// Generates crates/core/src/formats/pe_tables.rs from the name tables in
// horsicq's Formats project, the one XPEViewer and Detect It Easy are built on.
//
//   node tools/petables.mjs
//
// These are the names for the numbers in a PE: machine types, subsystems, the
// bits of each characteristics field, relocation and debug and resource types.
// Writing them out by hand means writing forty magic numbers from memory and
// getting some of them wrong; taking them from the project that maintains them
// means a newer PE stays readable by bumping a hash.
//
// This is a generator, not a copy. Update by changing COMMIT and running it
// again, the same as the signature rules: what has to stay true is that
// updating is a command rather than a diff to merge by hand.

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/** The Formats commit these tables come from. Bump to update. */
const COMMIT = "master";
const SOURCE = "https://raw.githubusercontent.com/horsicq/Formats";

// Which tables to take, what to call them here, and whether the numbers are
// values of one field or bits of it.
const TABLES = [
  { from: "ImageFileHeaderMachines", as: "MACHINE", kind: "enum" },
  { from: "ImageFileHeaderCharacteristics", as: "CHARACTERISTICS", kind: "flags" },
  { from: "ImageOptionalHeaderMagic", as: "OPTIONAL_MAGIC", kind: "enum" },
  { from: "ImageOptionalHeaderSubsystem", as: "SUBSYSTEM", kind: "enum" },
  { from: "ImageOptionalHeaderDllCharacteristics", as: "DLL_CHARACTERISTICS", kind: "flags" },
  { from: "ImageOptionalHeaderDataDirectory", as: "DIRECTORY", kind: "enum" },
  { from: "ImageSectionHeaderFlags", as: "SECTION_FLAGS", kind: "flags" },
  { from: "ImageRelBased", as: "RELOCATION", kind: "enum" },
  { from: "DebugTypes", as: "DEBUG_TYPE", kind: "enum" },
  { from: "ResourceTypes", as: "RESOURCE_TYPE", kind: "enum" },
  { from: "ComImageFlags", as: "COM_IMAGE_FLAGS", kind: "flags" },
];

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const head = execFileSync("git", ["ls-remote", "https://github.com/horsicq/Formats.git", COMMIT], { encoding: "utf8" })
  .split(/\s+/)[0];
if (!head) throw new Error(`cannot resolve ${COMMIT}`);
const source = await fetch(`${SOURCE}/${head}/exec/xpe.cpp`).then((r) => {
  if (!r.ok) throw new Error(`xpe.cpp: ${r.status}`);
  return r.text();
});

/** Everything between `_TABLE_XPE_<name>[] = {` and its closing brace. */
function tableBody(name) {
  const at = source.indexOf(`_TABLE_XPE_${name}[] = {`);
  if (at === -1) throw new Error(`no table ${name}`);
  const start = source.indexOf("{", at + `_TABLE_XPE_${name}`.length) + 1;
  const end = source.indexOf("};", start);
  return source.slice(start, end);
}

/** `{0x014c, "I386"}` pairs, in the order the table lists them. */
function entries(name) {
  const out = [];
  for (const m of tableBody(name).matchAll(/\{\s*(0[xX][0-9a-fA-F]+|\d+)\s*,\s*"([^"]*)"\s*\}/g)) {
    out.push({ value: BigInt(m[1]), name: m[2] });
  }
  if (out.length === 0) throw new Error(`table ${name} came out empty`);
  return out;
}

/**
 * `LARGE_ADDRESS_AWARE` becomes `large address aware`. The identifier is the
 * upstream project's; how it reads on screen is ours, and every other template
 * here names its values in lower case words.
 */
const readable = (id) => id.toLowerCase().replace(/_/g, " ").trim();

/** Which bit a flag's value stands for, or null when it is not a single bit. */
function bitOf(v) {
  if (v <= 0n) return null;
  let bit = 0n;
  let x = v;
  while ((x & 1n) === 0n) {
    x >>= 1n;
    bit += 1n;
  }
  return x === 1n ? Number(bit) : null;
}

let out = `//! Names for the numbers in a PE, generated by \`node tools/petables.mjs\`.
//!
//! Do not edit. These come from the \`Formats\` project that XPEViewer and
//! Detect It Easy are built on, at commit \`${head}\`, and are used under its
//! MIT licence. The identifiers are that project's; the lower case reading of
//! them is this one's, to match how every other template here names a value.

`;

for (const { from, as, kind } of TABLES) {
  const rows = entries(from);
  if (kind === "flags") {
    const bits = rows.map((r) => ({ bit: bitOf(r.value), name: r.name })).filter((r) => r.bit !== null);
    const dropped = rows.length - bits.length;
    out += `/// ${from}, ${bits.length} named bits`;
    out += dropped > 0 ? `. ${dropped} entries cover more than one bit and name a value rather than a flag.\n` : `.\n`;
    out += `pub const ${as}: &[(u32, &str)] = &[\n`;
    for (const b of bits) out += `    (${b.bit}, "${readable(b.name)}"),\n`;
    out += `];\n\n`;
  } else {
    out += `/// ${from}, ${rows.length} named values.\n`;
    out += `pub const ${as}: &[(i128, &str)] = &[\n`;
    for (const r of rows) out += `    (0x${r.value.toString(16)}, "${readable(r.name)}"),\n`;
    out += `];\n\n`;
  }
  console.log(`${as}: ${rows.length} from ${from}`);
}

writeFileSync(join(ROOT, "crates", "core", "src", "formats", "pe_tables.rs"), out, "utf8");
console.log(`Formats at ${head}`);
