// The ImHex pattern library: the list of what is in it, and the fetch.
//
// The library is 310 patterns under one GPL-2.0 repository, so none of it is
// copied into Qubero. What is committed here is metadata, `hexpat-index.json`,
// regenerated by `tools/hexpat_index.mjs`: each pattern's path, what it says it
// describes, who wrote it, what it pins as a magic, which other files it needs,
// and how much of it the converter can express.
//
// Nothing here touches the network until `fetchPattern` is called, and that is
// called from a click and nowhere else. The files it fetches are held in the
// page for that session and never stored.

/** One pattern in the library, as the index records it. */
export type LibraryEntry = {
  /** Where it is under `patterns/`, e.g. `fs/mbr.hexpat`. */
  readonly path: string;
  /** The file's stem, which is what the template goes by once it is applied. */
  readonly name: string;
  /** `#pragma description`, empty for a pattern that carries none. */
  readonly description: string;
  /** `#pragma author`, empty for a pattern that carries none. */
  readonly author: string;
  /** What `#pragma magic` pins, or null. */
  readonly magic: { readonly at: number; readonly bytes: string } | null;
  /** The other files it needs, as paths inside the repository. */
  readonly needs: readonly string[];
  /** How much of it the converter expressed the last time the index was
   *  regenerated: 0 for all of it, a count of what it could not say, and null
   *  for a pattern the converter refuses. */
  readonly gaps: number | null;
};

export type Library = {
  readonly source: string;
  readonly licence: string;
  readonly patterns: readonly LibraryEntry[];
};

/** Where the index is served from, beside the page. */
const INDEX_URL = "hexpat-index.json";

/** The repository the patterns are fetched from, at the revision the index was
 *  built against. `master`, as the upstream project publishes no tags for the
 *  pattern collection. */
export const RAW_BASE = "https://raw.githubusercontent.com/WerWolv/ImHex-Patterns/master/";

/** Read the committed index. Local to the page; no pattern text is in it. */
export async function loadLibrary(): Promise<Library> {
  const response = await fetch(INDEX_URL);
  if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
  const json = (await response.json()) as Library;
  return json;
}

/** The files a pattern is fetched as: the pattern itself, then everything it
 *  needs, each as a path inside the repository. */
export function filesFor(entry: LibraryEntry): readonly string[] {
  return [`patterns/${entry.path}`, ...entry.needs];
}

/** What came back from the library: the pattern's own text, and every file it
 *  needs keyed by the path an `#include` or an `import` resolves to. */
export type Fetched = {
  readonly text: string;
  readonly includes: Record<string, string>;
};

/**
 * Fetch one pattern and the files it needs.
 *
 * Called from a click and from nowhere else: picking a row in the list shows
 * what would be downloaded and asks, and this is what the asking leads to.
 *
 * An include is keyed by its path with the `includes/` or `patterns/` root
 * taken off, which is the form the converter resolves: `includes/std/mem.pat`
 * becomes `std/mem.pat`.
 */
export async function fetchPattern(entry: LibraryEntry): Promise<Fetched> {
  const get = async (path: string): Promise<string> => {
    const response = await fetch(RAW_BASE + path);
    if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
    return response.text();
  };
  const text = await get(`patterns/${entry.path}`);
  const includes: Record<string, string> = {};
  for (const path of entry.needs) {
    includes[includeKey(path)] = await get(path);
  }
  return { text, includes };
}

/** The path a repository file answers an `#include` or an `import` by. */
export function includeKey(path: string): string {
  return path.replace(/^includes\//, "").replace(/^patterns\//, "");
}

/** Which entries match what was typed. Name first, then description and author,
 *  so typing a format's name puts that format at the top. */
export function search(patterns: readonly LibraryEntry[], query: string): readonly LibraryEntry[] {
  const q = query.trim().toLowerCase();
  if (q === "") return patterns;
  const byName = patterns.filter((p) => p.name.toLowerCase().includes(q));
  const rest = patterns.filter(
    (p) => !byName.includes(p) && (p.description.toLowerCase().includes(q) || p.author.toLowerCase().includes(q) || p.path.toLowerCase().includes(q)),
  );
  return [...byName, ...rest];
}
