//! The eBPF instruction set: what each opcode byte means, and the helper
//! functions a `call` can name.
//!
//! The table is RFC 9669's instruction registry, appendix A, transcribed as
//! written. A row pins the fields that have to hold a particular value for
//! that meaning: `mov` is one opcode whose offset says whether the move sign
//! extends, and the atomic operations are two opcodes whose immediate says
//! which operation. `None` is the registry's "any", a field the opcode leaves
//! free.
//!
//! The forms are the registry's own descriptions, with `dst`, `src`, `imm`,
//! `offset` and `next_imm` left standing. Substituting the registers and
//! numbers an instruction actually holds is what [`super::bpf_disasm`] does,
//! so the line a person reads and the line the standard writes are the same
//! sentence.

/// One row of the instruction registry.
pub struct Op {
    pub code: u8,
    /// The source register field, when the opcode uses it to say which
    /// meaning it has rather than which register to read.
    pub src: Option<u8>,
    pub off: Option<i16>,
    pub imm: Option<i32>,
    /// What the instruction does, in the registry's words.
    pub form: &'static str,
}

/// Every opcode the standard defines, in opcode order.
pub const OPS: &[Op] = &[
    Op { code: 0x00, src: Some(0), off: Some(0), imm: None, form: "(additional immediate value)" },
    Op { code: 0x04, src: Some(0), off: Some(0), imm: None, form: "dst = (u32)((u32)dst + (u32)imm)" },
    Op { code: 0x05, src: Some(0), off: None, imm: Some(0), form: "goto +offset" },
    Op { code: 0x06, src: Some(0), off: Some(0), imm: None, form: "goto +imm" },
    Op { code: 0x07, src: Some(0), off: Some(0), imm: None, form: "dst += imm" },
    Op { code: 0x0c, src: None, off: Some(0), imm: Some(0), form: "dst = (u32)((u32)dst + (u32)src)" },
    Op { code: 0x0f, src: None, off: Some(0), imm: Some(0), form: "dst += src" },
    Op { code: 0x14, src: Some(0), off: Some(0), imm: None, form: "dst = (u32)((u32)dst - (u32)imm)" },
    Op { code: 0x15, src: Some(0), off: None, imm: None, form: "if dst == imm goto +offset" },
    Op { code: 0x16, src: Some(0), off: None, imm: None, form: "if (u32)dst == imm goto +offset" },
    Op { code: 0x17, src: Some(0), off: Some(0), imm: None, form: "dst -= imm" },
    Op { code: 0x18, src: Some(0), off: Some(0), imm: None, form: "dst = (next_imm << 32) | imm" },
    Op { code: 0x18, src: Some(1), off: Some(0), imm: None, form: "dst = map_by_fd(imm)" },
    Op { code: 0x18, src: Some(2), off: Some(0), imm: None, form: "dst = map_val(map_by_fd(imm)) + next_imm" },
    Op { code: 0x18, src: Some(3), off: Some(0), imm: None, form: "dst = var_addr(imm)" },
    Op { code: 0x18, src: Some(4), off: Some(0), imm: None, form: "dst = code_addr(imm)" },
    Op { code: 0x18, src: Some(5), off: Some(0), imm: None, form: "dst = map_by_idx(imm)" },
    Op { code: 0x18, src: Some(6), off: Some(0), imm: None, form: "dst = map_val(map_by_idx(imm)) + next_imm" },
    Op { code: 0x1c, src: None, off: Some(0), imm: Some(0), form: "dst = (u32)((u32)dst - (u32)src)" },
    Op { code: 0x1d, src: None, off: None, imm: Some(0), form: "if dst == src goto +offset" },
    Op { code: 0x1e, src: None, off: None, imm: Some(0), form: "if (u32)dst == (u32)src goto +offset" },
    Op { code: 0x1f, src: None, off: Some(0), imm: Some(0), form: "dst -= src" },
    Op { code: 0x20, src: Some(0), off: Some(0), imm: None, form: "(deprecated, implementation-specific)" },
    Op { code: 0x24, src: Some(0), off: Some(0), imm: None, form: "dst = (u32)(dst * imm)" },
    Op { code: 0x25, src: Some(0), off: None, imm: None, form: "if dst > imm goto +offset" },
    Op { code: 0x26, src: Some(0), off: None, imm: None, form: "if (u32)dst > imm goto +offset" },
    Op { code: 0x27, src: Some(0), off: Some(0), imm: None, form: "dst *= imm" },
    Op { code: 0x28, src: Some(0), off: Some(0), imm: None, form: "(deprecated, implementation-specific)" },
    Op { code: 0x2c, src: None, off: Some(0), imm: Some(0), form: "dst = (u32)(dst * src)" },
    Op { code: 0x2d, src: None, off: None, imm: Some(0), form: "if dst > src goto +offset" },
    Op { code: 0x2e, src: None, off: None, imm: Some(0), form: "if (u32)dst > (u32)src goto +offset" },
    Op { code: 0x2f, src: None, off: Some(0), imm: Some(0), form: "dst *= src" },
    Op { code: 0x30, src: Some(0), off: Some(0), imm: None, form: "(deprecated, implementation-specific)" },
    Op { code: 0x34, src: Some(0), off: Some(0), imm: None, form: "dst = (u32)((imm != 0) ? ((u32)dst / (u32)imm) : 0)" },
    Op { code: 0x34, src: Some(0), off: Some(1), imm: None, form: "dst = (u32)((imm != 0) ? ((s32)dst s/ imm) : 0)" },
    Op { code: 0x35, src: Some(0), off: None, imm: None, form: "if dst >= imm goto +offset" },
    Op { code: 0x36, src: Some(0), off: None, imm: None, form: "if (u32)dst >= imm goto +offset" },
    Op { code: 0x37, src: Some(0), off: Some(0), imm: None, form: "dst = (imm != 0) ? (dst / (u32)imm) : 0" },
    Op { code: 0x37, src: Some(0), off: Some(1), imm: None, form: "dst = (imm != 0) ? (dst s/ imm) : 0" },
    Op { code: 0x3c, src: None, off: Some(0), imm: Some(0), form: "dst = (u32)((src != 0) ? ((u32)dst / (u32)src) : 0)" },
    Op { code: 0x3c, src: None, off: Some(1), imm: Some(0), form: "dst = (u32)((src != 0) ? ((s32)dst s/(s32)src) : 0)" },
    Op { code: 0x3d, src: None, off: None, imm: Some(0), form: "if dst >= src goto +offset" },
    Op { code: 0x3e, src: None, off: None, imm: Some(0), form: "if (u32)dst >= (u32)src goto +offset" },
    Op { code: 0x3f, src: None, off: Some(0), imm: Some(0), form: "dst = (src != 0) ? (dst / src) : 0" },
    Op { code: 0x3f, src: None, off: Some(1), imm: Some(0), form: "dst = (src != 0) ? (dst s/ src) : 0" },
    Op { code: 0x40, src: None, off: Some(0), imm: None, form: "(deprecated, implementation-specific)" },
    Op { code: 0x44, src: Some(0), off: Some(0), imm: None, form: "dst = (u32)(dst | imm)" },
    Op { code: 0x45, src: Some(0), off: None, imm: None, form: "if dst & imm goto +offset" },
    Op { code: 0x46, src: Some(0), off: None, imm: None, form: "if (u32)dst & imm goto +offset" },
    Op { code: 0x47, src: Some(0), off: Some(0), imm: None, form: "dst |= imm" },
    Op { code: 0x48, src: None, off: Some(0), imm: None, form: "(deprecated, implementation-specific)" },
    Op { code: 0x4c, src: None, off: Some(0), imm: Some(0), form: "dst = (u32)(dst | src)" },
    Op { code: 0x4d, src: None, off: None, imm: Some(0), form: "if dst & src goto +offset" },
    Op { code: 0x4e, src: None, off: None, imm: Some(0), form: "if (u32)dst & (u32)src goto +offset" },
    Op { code: 0x4f, src: None, off: Some(0), imm: Some(0), form: "dst |= src" },
    Op { code: 0x50, src: None, off: Some(0), imm: None, form: "(deprecated, implementation-specific)" },
    Op { code: 0x54, src: Some(0), off: Some(0), imm: None, form: "dst = (u32)(dst & imm)" },
    Op { code: 0x55, src: Some(0), off: None, imm: None, form: "if dst != imm goto +offset" },
    Op { code: 0x56, src: Some(0), off: None, imm: None, form: "if (u32)dst != imm goto +offset" },
    Op { code: 0x57, src: Some(0), off: Some(0), imm: None, form: "dst &= imm" },
    Op { code: 0x5c, src: None, off: Some(0), imm: Some(0), form: "dst = (u32)(dst & src)" },
    Op { code: 0x5d, src: None, off: None, imm: Some(0), form: "if dst != src goto +offset" },
    Op { code: 0x5e, src: None, off: None, imm: Some(0), form: "if (u32)dst != (u32)src goto +offset" },
    Op { code: 0x5f, src: None, off: Some(0), imm: Some(0), form: "dst &= src" },
    Op { code: 0x61, src: None, off: None, imm: Some(0), form: "dst = *(u32 *)(src + offset)" },
    Op { code: 0x62, src: Some(0), off: None, imm: None, form: "*(u32 *)(dst + offset) = imm" },
    Op { code: 0x63, src: None, off: None, imm: Some(0), form: "*(u32 *)(dst + offset) = src" },
    Op { code: 0x64, src: Some(0), off: Some(0), imm: None, form: "dst = (u32)(dst << imm)" },
    Op { code: 0x65, src: Some(0), off: None, imm: None, form: "if dst s> imm goto +offset" },
    Op { code: 0x66, src: Some(0), off: None, imm: None, form: "if (s32)dst s> (s32)imm goto +offset" },
    Op { code: 0x67, src: Some(0), off: Some(0), imm: None, form: "dst <<= imm" },
    Op { code: 0x69, src: None, off: None, imm: Some(0), form: "dst = *(u16 *)(src + offset)" },
    Op { code: 0x6a, src: Some(0), off: None, imm: None, form: "*(u16 *)(dst + offset) = imm" },
    Op { code: 0x6b, src: None, off: None, imm: Some(0), form: "*(u16 *)(dst + offset) = src" },
    Op { code: 0x6c, src: None, off: Some(0), imm: Some(0), form: "dst = (u32)(dst << src)" },
    Op { code: 0x6d, src: None, off: None, imm: Some(0), form: "if dst s> src goto +offset" },
    Op { code: 0x6e, src: None, off: None, imm: Some(0), form: "if (s32)dst s> (s32)src goto +offset" },
    Op { code: 0x6f, src: None, off: Some(0), imm: Some(0), form: "dst <<= src" },
    Op { code: 0x71, src: None, off: None, imm: Some(0), form: "dst = *(u8 *)(src + offset)" },
    Op { code: 0x72, src: Some(0), off: None, imm: None, form: "*(u8 *)(dst + offset) = imm" },
    Op { code: 0x73, src: None, off: None, imm: Some(0), form: "*(u8 *)(dst + offset) = src" },
    Op { code: 0x74, src: Some(0), off: Some(0), imm: None, form: "dst = (u32)(dst >> imm)" },
    Op { code: 0x75, src: Some(0), off: None, imm: None, form: "if dst s>= imm goto +offset" },
    Op { code: 0x76, src: Some(0), off: None, imm: None, form: "if (s32)dst s>= (s32)imm goto +offset" },
    Op { code: 0x77, src: Some(0), off: Some(0), imm: None, form: "dst >>= imm" },
    Op { code: 0x79, src: None, off: None, imm: Some(0), form: "dst = *(u64 *)(src + offset)" },
    Op { code: 0x7a, src: Some(0), off: None, imm: None, form: "*(u64 *)(dst + offset) = imm" },
    Op { code: 0x7b, src: None, off: None, imm: Some(0), form: "*(u64 *)(dst + offset) = src" },
    Op { code: 0x7c, src: None, off: Some(0), imm: Some(0), form: "dst = (u32)(dst >> src)" },
    Op { code: 0x7d, src: None, off: None, imm: Some(0), form: "if dst s>= src goto +offset" },
    Op { code: 0x7e, src: None, off: None, imm: Some(0), form: "if (s32)dst s>= (s32)src goto +offset" },
    Op { code: 0x7f, src: None, off: Some(0), imm: Some(0), form: "dst >>= src" },
    Op { code: 0x84, src: Some(0), off: Some(0), imm: Some(0), form: "dst = (u32)-dst" },
    Op { code: 0x85, src: Some(0), off: Some(0), imm: None, form: "call helper function by static ID" },
    Op { code: 0x85, src: Some(1), off: Some(0), imm: None, form: "call PC += imm" },
    Op { code: 0x85, src: Some(2), off: Some(0), imm: None, form: "call helper function by BTF ID" },
    Op { code: 0x87, src: Some(0), off: Some(0), imm: Some(0), form: "dst = -dst" },
    Op { code: 0x94, src: Some(0), off: Some(0), imm: None, form: "dst = (u32)((imm != 0)?((u32)dst % (u32)imm) : dst)" },
    Op { code: 0x94, src: Some(0), off: Some(1), imm: None, form: "dst = (u32)((imm != 0) ? ((s32)dst s% imm) : dst)" },
    Op { code: 0x95, src: Some(0), off: Some(0), imm: Some(0), form: "return" },
    Op { code: 0x97, src: Some(0), off: Some(0), imm: None, form: "dst = (imm != 0) ? (dst % (u32)imm) : dst" },
    Op { code: 0x97, src: Some(0), off: Some(1), imm: None, form: "dst = (imm != 0) ? (dst s% imm) : dst" },
    Op { code: 0x9c, src: None, off: Some(0), imm: Some(0), form: "dst = (u32)((src != 0)?((u32)dst % (u32)src) : dst)" },
    Op { code: 0x9c, src: None, off: Some(1), imm: Some(0), form: "dst = (u32)((src != 0)?((s32)dst s% (s32)src) :dst)" },
    Op { code: 0x9f, src: None, off: Some(0), imm: Some(0), form: "dst = (src != 0) ? (dst % src) : dst" },
    Op { code: 0x9f, src: None, off: Some(1), imm: Some(0), form: "dst = (src != 0) ? (dst s% src) : dst" },
    Op { code: 0xa4, src: Some(0), off: Some(0), imm: None, form: "dst = (u32)(dst ^ imm)" },
    Op { code: 0xa5, src: Some(0), off: None, imm: None, form: "if dst < imm goto +offset" },
    Op { code: 0xa6, src: Some(0), off: None, imm: None, form: "if (u32)dst < imm goto +offset" },
    Op { code: 0xa7, src: Some(0), off: Some(0), imm: None, form: "dst ^= imm" },
    Op { code: 0xac, src: None, off: Some(0), imm: Some(0), form: "dst = (u32)(dst ^ src)" },
    Op { code: 0xad, src: None, off: None, imm: Some(0), form: "if dst < src goto +offset" },
    Op { code: 0xae, src: None, off: None, imm: Some(0), form: "if (u32)dst < (u32)src goto +offset" },
    Op { code: 0xaf, src: None, off: Some(0), imm: Some(0), form: "dst ^= src" },
    Op { code: 0xb4, src: Some(0), off: Some(0), imm: None, form: "dst = (u32) imm" },
    Op { code: 0xb5, src: Some(0), off: None, imm: None, form: "if dst <= imm goto +offset" },
    Op { code: 0xb6, src: Some(0), off: None, imm: None, form: "if (u32)dst <= imm goto +offset" },
    Op { code: 0xb7, src: Some(0), off: Some(0), imm: None, form: "dst = imm" },
    Op { code: 0xbc, src: None, off: Some(0), imm: Some(0), form: "dst = (u32) src" },
    Op { code: 0xbc, src: None, off: Some(8), imm: Some(0), form: "dst = (u32) (s32) (s8) src" },
    Op { code: 0xbc, src: None, off: Some(16), imm: Some(0), form: "dst = (u32) (s32) (s16) src" },
    Op { code: 0xbd, src: None, off: None, imm: Some(0), form: "if dst <= src goto +offset" },
    Op { code: 0xbe, src: None, off: None, imm: Some(0), form: "if (u32)dst <= (u32)src goto +offset" },
    Op { code: 0xbf, src: None, off: Some(0), imm: Some(0), form: "dst = src" },
    Op { code: 0xbf, src: None, off: Some(8), imm: Some(0), form: "dst = (s64) (s8) src" },
    Op { code: 0xbf, src: None, off: Some(16), imm: Some(0), form: "dst = (s64) (s16) src" },
    Op { code: 0xbf, src: None, off: Some(32), imm: Some(0), form: "dst = (s64) (s32) src" },
    Op { code: 0xc3, src: None, off: None, imm: Some(0), form: "lock *(u32 *)(dst + offset) += src" },
    Op { code: 0xc3, src: None, off: None, imm: Some(1), form: "src = atomic_fetch_add_32((u32 *)(dst + offset), src)" },
    Op { code: 0xc3, src: None, off: None, imm: Some(64), form: "lock *(u32 *)(dst + offset) |= src" },
    Op { code: 0xc3, src: None, off: None, imm: Some(65), form: "src = atomic_fetch_or_32((u32 *)(dst + offset), src)" },
    Op { code: 0xc3, src: None, off: None, imm: Some(80), form: "lock *(u32 *)(dst + offset) &= src" },
    Op { code: 0xc3, src: None, off: None, imm: Some(81), form: "src = atomic_fetch_and_32((u32 *)(dst + offset), src)" },
    Op { code: 0xc3, src: None, off: None, imm: Some(160), form: "lock *(u32 *)(dst + offset) ^= src" },
    Op { code: 0xc3, src: None, off: None, imm: Some(161), form: "src = atomic_fetch_xor_32((u32 *)(dst + offset), src)" },
    Op { code: 0xc3, src: None, off: None, imm: Some(225), form: "src = xchg_32((u32 *)(dst + offset), src)" },
    Op { code: 0xc3, src: None, off: None, imm: Some(241), form: "r0 = cmpxchg_32((u32 *)(dst + offset), r0, src)" },
    Op { code: 0xc4, src: Some(0), off: Some(0), imm: None, form: "dst = (u32)(dst s>> imm)" },
    Op { code: 0xc5, src: Some(0), off: None, imm: None, form: "if dst s< imm goto +offset" },
    Op { code: 0xc6, src: Some(0), off: None, imm: None, form: "if (s32)dst s< (s32)imm goto +offset" },
    Op { code: 0xc7, src: Some(0), off: Some(0), imm: None, form: "dst s>>= imm" },
    Op { code: 0xcc, src: None, off: Some(0), imm: Some(0), form: "dst = (u32)(dst s>> src)" },
    Op { code: 0xcd, src: None, off: None, imm: Some(0), form: "if dst s< src goto +offset" },
    Op { code: 0xce, src: None, off: None, imm: Some(0), form: "if (s32)dst s< (s32)src goto +offset" },
    Op { code: 0xcf, src: None, off: Some(0), imm: Some(0), form: "dst s>>= src" },
    Op { code: 0xd4, src: Some(0), off: Some(0), imm: Some(16), form: "dst = htole16(dst)" },
    Op { code: 0xd4, src: Some(0), off: Some(0), imm: Some(32), form: "dst = htole32(dst)" },
    Op { code: 0xd4, src: Some(0), off: Some(0), imm: Some(64), form: "dst = htole64(dst)" },
    Op { code: 0xd5, src: Some(0), off: None, imm: None, form: "if dst s<= imm goto +offset" },
    Op { code: 0xd6, src: Some(0), off: None, imm: None, form: "if (s32)dst s<= (s32)imm goto +offset" },
    Op { code: 0xd7, src: Some(0), off: Some(0), imm: Some(16), form: "dst = bswap16(dst)" },
    Op { code: 0xd7, src: Some(0), off: Some(0), imm: Some(32), form: "dst = bswap32(dst)" },
    Op { code: 0xd7, src: Some(0), off: Some(0), imm: Some(64), form: "dst = bswap64(dst)" },
    Op { code: 0xdb, src: None, off: None, imm: Some(0), form: "lock *(u64 *)(dst + offset) += src" },
    Op { code: 0xdb, src: None, off: None, imm: Some(1), form: "src = atomic_fetch_add_64((u64 *)(dst + offset), src)" },
    Op { code: 0xdb, src: None, off: None, imm: Some(64), form: "lock *(u64 *)(dst + offset) |= src" },
    Op { code: 0xdb, src: None, off: None, imm: Some(65), form: "src = atomic_fetch_or_64((u64 *)(dst + offset), src)" },
    Op { code: 0xdb, src: None, off: None, imm: Some(80), form: "lock *(u64 *)(dst + offset) &= src" },
    Op { code: 0xdb, src: None, off: None, imm: Some(81), form: "src = atomic_fetch_and_64((u64 *)(dst + offset), src)" },
    Op { code: 0xdb, src: None, off: None, imm: Some(160), form: "lock *(u64 *)(dst + offset) ^= src" },
    Op { code: 0xdb, src: None, off: None, imm: Some(161), form: "src = atomic_fetch_xor_64((u64 *)(dst + offset), src)" },
    Op { code: 0xdb, src: None, off: None, imm: Some(225), form: "src = xchg_64((u64 *)(dst + offset), src)" },
    Op { code: 0xdb, src: None, off: None, imm: Some(241), form: "r0 = cmpxchg_64((u64 *)(dst + offset), r0, src)" },
    Op { code: 0xdc, src: Some(0), off: Some(0), imm: Some(16), form: "dst = htobe16(dst)" },
    Op { code: 0xdc, src: Some(0), off: Some(0), imm: Some(32), form: "dst = htobe32(dst)" },
    Op { code: 0xdc, src: Some(0), off: Some(0), imm: Some(64), form: "dst = htobe64(dst)" },
    Op { code: 0xdd, src: None, off: None, imm: Some(0), form: "if dst s<= src goto +offset" },
    Op { code: 0xde, src: None, off: None, imm: Some(0), form: "if (s32)dst s<= (s32)src goto +offset" },
];

/// A label per opcode byte, for the field itself. Where one byte has several
/// meanings the label is the shape they share; which of them an instruction
/// has takes the other fields, and [`form`] reads those.
pub const OPCODES: &[(i128, &str)] = &[
    (0x00, "(additional immediate value)"),
    (0x04, "dst = (u32)((u32)dst + (u32)imm)"),
    (0x05, "goto +offset"),
    (0x06, "goto +imm"),
    (0x07, "dst += imm"),
    (0x0c, "dst = (u32)((u32)dst + (u32)src)"),
    (0x0f, "dst += src"),
    (0x14, "dst = (u32)((u32)dst - (u32)imm)"),
    (0x15, "if dst == imm goto +offset"),
    (0x16, "if (u32)dst == imm goto +offset"),
    (0x17, "dst -= imm"),
    (0x18, "dst = 64-bit immediate"),
    (0x1c, "dst = (u32)((u32)dst - (u32)src)"),
    (0x1d, "if dst == src goto +offset"),
    (0x1e, "if (u32)dst == (u32)src goto +offset"),
    (0x1f, "dst -= src"),
    (0x20, "(deprecated, implementation-specific)"),
    (0x24, "dst = (u32)(dst * imm)"),
    (0x25, "if dst > imm goto +offset"),
    (0x26, "if (u32)dst > imm goto +offset"),
    (0x27, "dst *= imm"),
    (0x28, "(deprecated, implementation-specific)"),
    (0x2c, "dst = (u32)(dst * src)"),
    (0x2d, "if dst > src goto +offset"),
    (0x2e, "if (u32)dst > (u32)src goto +offset"),
    (0x2f, "dst *= src"),
    (0x30, "(deprecated, implementation-specific)"),
    (0x34, "dst = (u32)(dst / imm)"),
    (0x35, "if dst >= imm goto +offset"),
    (0x36, "if (u32)dst >= imm goto +offset"),
    (0x37, "dst = dst / imm"),
    (0x3c, "dst = (u32)(dst / src)"),
    (0x3d, "if dst >= src goto +offset"),
    (0x3e, "if (u32)dst >= (u32)src goto +offset"),
    (0x3f, "dst = dst / src"),
    (0x40, "(deprecated, implementation-specific)"),
    (0x44, "dst = (u32)(dst | imm)"),
    (0x45, "if dst & imm goto +offset"),
    (0x46, "if (u32)dst & imm goto +offset"),
    (0x47, "dst |= imm"),
    (0x48, "(deprecated, implementation-specific)"),
    (0x4c, "dst = (u32)(dst | src)"),
    (0x4d, "if dst & src goto +offset"),
    (0x4e, "if (u32)dst & (u32)src goto +offset"),
    (0x4f, "dst |= src"),
    (0x50, "(deprecated, implementation-specific)"),
    (0x54, "dst = (u32)(dst & imm)"),
    (0x55, "if dst != imm goto +offset"),
    (0x56, "if (u32)dst != imm goto +offset"),
    (0x57, "dst &= imm"),
    (0x5c, "dst = (u32)(dst & src)"),
    (0x5d, "if dst != src goto +offset"),
    (0x5e, "if (u32)dst != (u32)src goto +offset"),
    (0x5f, "dst &= src"),
    (0x61, "dst = *(u32 *)(src + offset)"),
    (0x62, "*(u32 *)(dst + offset) = imm"),
    (0x63, "*(u32 *)(dst + offset) = src"),
    (0x64, "dst = (u32)(dst << imm)"),
    (0x65, "if dst s> imm goto +offset"),
    (0x66, "if (s32)dst s> (s32)imm goto +offset"),
    (0x67, "dst <<= imm"),
    (0x69, "dst = *(u16 *)(src + offset)"),
    (0x6a, "*(u16 *)(dst + offset) = imm"),
    (0x6b, "*(u16 *)(dst + offset) = src"),
    (0x6c, "dst = (u32)(dst << src)"),
    (0x6d, "if dst s> src goto +offset"),
    (0x6e, "if (s32)dst s> (s32)src goto +offset"),
    (0x6f, "dst <<= src"),
    (0x71, "dst = *(u8 *)(src + offset)"),
    (0x72, "*(u8 *)(dst + offset) = imm"),
    (0x73, "*(u8 *)(dst + offset) = src"),
    (0x74, "dst = (u32)(dst >> imm)"),
    (0x75, "if dst s>= imm goto +offset"),
    (0x76, "if (s32)dst s>= (s32)imm goto +offset"),
    (0x77, "dst >>= imm"),
    (0x79, "dst = *(u64 *)(src + offset)"),
    (0x7a, "*(u64 *)(dst + offset) = imm"),
    (0x7b, "*(u64 *)(dst + offset) = src"),
    (0x7c, "dst = (u32)(dst >> src)"),
    (0x7d, "if dst s>= src goto +offset"),
    (0x7e, "if (s32)dst s>= (s32)src goto +offset"),
    (0x7f, "dst >>= src"),
    (0x84, "dst = (u32)-dst"),
    (0x85, "call"),
    (0x87, "dst = -dst"),
    (0x94, "dst = (u32)(dst % imm)"),
    (0x95, "return"),
    (0x97, "dst = dst % imm"),
    (0x9c, "dst = (u32)(dst % src)"),
    (0x9f, "dst = dst % src"),
    (0xa4, "dst = (u32)(dst ^ imm)"),
    (0xa5, "if dst < imm goto +offset"),
    (0xa6, "if (u32)dst < imm goto +offset"),
    (0xa7, "dst ^= imm"),
    (0xac, "dst = (u32)(dst ^ src)"),
    (0xad, "if dst < src goto +offset"),
    (0xae, "if (u32)dst < (u32)src goto +offset"),
    (0xaf, "dst ^= src"),
    (0xb4, "dst = (u32) imm"),
    (0xb5, "if dst <= imm goto +offset"),
    (0xb6, "if (u32)dst <= imm goto +offset"),
    (0xb7, "dst = imm"),
    (0xbc, "dst = (u32) src"),
    (0xbd, "if dst <= src goto +offset"),
    (0xbe, "if (u32)dst <= (u32)src goto +offset"),
    (0xbf, "dst = src"),
    (0xc3, "atomic 32-bit at (dst + offset)"),
    (0xc4, "dst = (u32)(dst s>> imm)"),
    (0xc5, "if dst s< imm goto +offset"),
    (0xc6, "if (s32)dst s< (s32)imm goto +offset"),
    (0xc7, "dst s>>= imm"),
    (0xcc, "dst = (u32)(dst s>> src)"),
    (0xcd, "if dst s< src goto +offset"),
    (0xce, "if (s32)dst s< (s32)src goto +offset"),
    (0xcf, "dst s>>= src"),
    (0xd4, "dst = htole(dst)"),
    (0xd5, "if dst s<= imm goto +offset"),
    (0xd6, "if (s32)dst s<= (s32)imm goto +offset"),
    (0xd7, "dst = bswap(dst)"),
    (0xdb, "atomic 64-bit at (dst + offset)"),
    (0xdc, "dst = htobe(dst)"),
    (0xdd, "if dst s<= src goto +offset"),
    (0xde, "if (s32)dst s<= (s32)src goto +offset"),
];

/// The registers, which are the same ten and a read-only frame pointer for
/// every eBPF program.
pub const REGS: &[(i128, &str)] = &[
    (0, "r0"), (1, "r1"), (2, "r2"), (3, "r3"), (4, "r4"), (5, "r5"),
    (6, "r6"), (7, "r7"), (8, "r8"), (9, "r9"), (10, "r10 (frame)"),
];

/// What this instruction does, as the registry writes it. The rows that pin
/// the most fields are asked first, so `dst = (s64) (s8) src` wins over
/// `dst = src` for the same opcode with an offset of 8.
pub fn form(code: u8, src: u8, off: i16, imm: i32) -> Option<&'static str> {
    let mut best: Option<(u8, &'static str)> = None;
    for op in OPS.iter().filter(|op| op.code == code) {
        if op.src.is_some_and(|v| v != src) || op.off.is_some_and(|v| v != off) || op.imm.is_some_and(|v| v != imm) {
            continue;
        }
        let pinned = op.src.is_some() as u8 + op.off.is_some() as u8 + op.imm.is_some() as u8;
        if best.is_none_or(|(b, _)| pinned > b) {
            best = Some((pinned, op.form));
        }
    }
    best.map(|(_, form)| form)
}

/// Whether the opcode takes sixteen bytes rather than eight. Only the load of
/// a 64-bit immediate does, and the eight bytes after it are a second
/// instruction word holding the top half of the number.
pub fn is_wide(code: u8) -> bool {
    code == 0x18
}

/// The helper functions the kernel offers, by the number a `call` writes in
/// its immediate. Transcribed from `___BPF_FUNC_MAPPER` in the kernel's
/// `include/uapi/linux/bpf.h`; the numbers are part of the ABI, so the list
/// only ever grows at the end.
pub const HELPERS: &[(i32, &str)] = &[
    (0, "bpf_unspec"),
    (1, "bpf_map_lookup_elem"),
    (2, "bpf_map_update_elem"),
    (3, "bpf_map_delete_elem"),
    (4, "bpf_probe_read"),
    (5, "bpf_ktime_get_ns"),
    (6, "bpf_trace_printk"),
    (7, "bpf_get_prandom_u32"),
    (8, "bpf_get_smp_processor_id"),
    (9, "bpf_skb_store_bytes"),
    (10, "bpf_l3_csum_replace"),
    (11, "bpf_l4_csum_replace"),
    (12, "bpf_tail_call"),
    (13, "bpf_clone_redirect"),
    (14, "bpf_get_current_pid_tgid"),
    (15, "bpf_get_current_uid_gid"),
    (16, "bpf_get_current_comm"),
    (17, "bpf_get_cgroup_classid"),
    (18, "bpf_skb_vlan_push"),
    (19, "bpf_skb_vlan_pop"),
    (20, "bpf_skb_get_tunnel_key"),
    (21, "bpf_skb_set_tunnel_key"),
    (22, "bpf_perf_event_read"),
    (23, "bpf_redirect"),
    (24, "bpf_get_route_realm"),
    (25, "bpf_perf_event_output"),
    (26, "bpf_skb_load_bytes"),
    (27, "bpf_get_stackid"),
    (28, "bpf_csum_diff"),
    (29, "bpf_skb_get_tunnel_opt"),
    (30, "bpf_skb_set_tunnel_opt"),
    (31, "bpf_skb_change_proto"),
    (32, "bpf_skb_change_type"),
    (33, "bpf_skb_under_cgroup"),
    (34, "bpf_get_hash_recalc"),
    (35, "bpf_get_current_task"),
    (36, "bpf_probe_write_user"),
    (37, "bpf_current_task_under_cgroup"),
    (38, "bpf_skb_change_tail"),
    (39, "bpf_skb_pull_data"),
    (40, "bpf_csum_update"),
    (41, "bpf_set_hash_invalid"),
    (42, "bpf_get_numa_node_id"),
    (43, "bpf_skb_change_head"),
    (44, "bpf_xdp_adjust_head"),
    (45, "bpf_probe_read_str"),
    (46, "bpf_get_socket_cookie"),
    (47, "bpf_get_socket_uid"),
    (48, "bpf_set_hash"),
    (49, "bpf_setsockopt"),
    (50, "bpf_skb_adjust_room"),
    (51, "bpf_redirect_map"),
    (52, "bpf_sk_redirect_map"),
    (53, "bpf_sock_map_update"),
    (54, "bpf_xdp_adjust_meta"),
    (55, "bpf_perf_event_read_value"),
    (56, "bpf_perf_prog_read_value"),
    (57, "bpf_getsockopt"),
    (58, "bpf_override_return"),
    (59, "bpf_sock_ops_cb_flags_set"),
    (60, "bpf_msg_redirect_map"),
    (61, "bpf_msg_apply_bytes"),
    (62, "bpf_msg_cork_bytes"),
    (63, "bpf_msg_pull_data"),
    (64, "bpf_bind"),
    (65, "bpf_xdp_adjust_tail"),
    (66, "bpf_skb_get_xfrm_state"),
    (67, "bpf_get_stack"),
    (68, "bpf_skb_load_bytes_relative"),
    (69, "bpf_fib_lookup"),
    (70, "bpf_sock_hash_update"),
    (71, "bpf_msg_redirect_hash"),
    (72, "bpf_sk_redirect_hash"),
    (73, "bpf_lwt_push_encap"),
    (74, "bpf_lwt_seg6_store_bytes"),
    (75, "bpf_lwt_seg6_adjust_srh"),
    (76, "bpf_lwt_seg6_action"),
    (77, "bpf_rc_repeat"),
    (78, "bpf_rc_keydown"),
    (79, "bpf_skb_cgroup_id"),
    (80, "bpf_get_current_cgroup_id"),
    (81, "bpf_get_local_storage"),
    (82, "bpf_sk_select_reuseport"),
    (83, "bpf_skb_ancestor_cgroup_id"),
    (84, "bpf_sk_lookup_tcp"),
    (85, "bpf_sk_lookup_udp"),
    (86, "bpf_sk_release"),
    (87, "bpf_map_push_elem"),
    (88, "bpf_map_pop_elem"),
    (89, "bpf_map_peek_elem"),
    (90, "bpf_msg_push_data"),
    (91, "bpf_msg_pop_data"),
    (92, "bpf_rc_pointer_rel"),
    (93, "bpf_spin_lock"),
    (94, "bpf_spin_unlock"),
    (95, "bpf_sk_fullsock"),
    (96, "bpf_tcp_sock"),
    (97, "bpf_skb_ecn_set_ce"),
    (98, "bpf_get_listener_sock"),
    (99, "bpf_skc_lookup_tcp"),
    (100, "bpf_tcp_check_syncookie"),
    (101, "bpf_sysctl_get_name"),
    (102, "bpf_sysctl_get_current_value"),
    (103, "bpf_sysctl_get_new_value"),
    (104, "bpf_sysctl_set_new_value"),
    (105, "bpf_strtol"),
    (106, "bpf_strtoul"),
    (107, "bpf_sk_storage_get"),
    (108, "bpf_sk_storage_delete"),
    (109, "bpf_send_signal"),
    (110, "bpf_tcp_gen_syncookie"),
    (111, "bpf_skb_output"),
    (112, "bpf_probe_read_user"),
    (113, "bpf_probe_read_kernel"),
    (114, "bpf_probe_read_user_str"),
    (115, "bpf_probe_read_kernel_str"),
    (116, "bpf_tcp_send_ack"),
    (117, "bpf_send_signal_thread"),
    (118, "bpf_jiffies64"),
    (119, "bpf_read_branch_records"),
    (120, "bpf_get_ns_current_pid_tgid"),
    (121, "bpf_xdp_output"),
    (122, "bpf_get_netns_cookie"),
    (123, "bpf_get_current_ancestor_cgroup_id"),
    (124, "bpf_sk_assign"),
    (125, "bpf_ktime_get_boot_ns"),
    (126, "bpf_seq_printf"),
    (127, "bpf_seq_write"),
    (128, "bpf_sk_cgroup_id"),
    (129, "bpf_sk_ancestor_cgroup_id"),
    (130, "bpf_ringbuf_output"),
    (131, "bpf_ringbuf_reserve"),
    (132, "bpf_ringbuf_submit"),
    (133, "bpf_ringbuf_discard"),
    (134, "bpf_ringbuf_query"),
    (135, "bpf_csum_level"),
    (136, "bpf_skc_to_tcp6_sock"),
    (137, "bpf_skc_to_tcp_sock"),
    (138, "bpf_skc_to_tcp_timewait_sock"),
    (139, "bpf_skc_to_tcp_request_sock"),
    (140, "bpf_skc_to_udp6_sock"),
    (141, "bpf_get_task_stack"),
    (142, "bpf_load_hdr_opt"),
    (143, "bpf_store_hdr_opt"),
    (144, "bpf_reserve_hdr_opt"),
    (145, "bpf_inode_storage_get"),
    (146, "bpf_inode_storage_delete"),
    (147, "bpf_d_path"),
    (148, "bpf_copy_from_user"),
    (149, "bpf_snprintf_btf"),
    (150, "bpf_seq_printf_btf"),
    (151, "bpf_skb_cgroup_classid"),
    (152, "bpf_redirect_neigh"),
    (153, "bpf_per_cpu_ptr"),
    (154, "bpf_this_cpu_ptr"),
    (155, "bpf_redirect_peer"),
    (156, "bpf_task_storage_get"),
    (157, "bpf_task_storage_delete"),
    (158, "bpf_get_current_task_btf"),
    (159, "bpf_bprm_opts_set"),
    (160, "bpf_ktime_get_coarse_ns"),
    (161, "bpf_ima_inode_hash"),
    (162, "bpf_sock_from_file"),
    (163, "bpf_check_mtu"),
    (164, "bpf_for_each_map_elem"),
    (165, "bpf_snprintf"),
    (166, "bpf_sys_bpf"),
    (167, "bpf_btf_find_by_name_kind"),
    (168, "bpf_sys_close"),
    (169, "bpf_timer_init"),
    (170, "bpf_timer_set_callback"),
    (171, "bpf_timer_start"),
    (172, "bpf_timer_cancel"),
    (173, "bpf_get_func_ip"),
    (174, "bpf_get_attach_cookie"),
    (175, "bpf_task_pt_regs"),
    (176, "bpf_get_branch_snapshot"),
    (177, "bpf_trace_vprintk"),
    (178, "bpf_skc_to_unix_sock"),
    (179, "bpf_kallsyms_lookup_name"),
    (180, "bpf_find_vma"),
    (181, "bpf_loop"),
    (182, "bpf_strncmp"),
    (183, "bpf_get_func_arg"),
    (184, "bpf_get_func_ret"),
    (185, "bpf_get_func_arg_cnt"),
    (186, "bpf_get_retval"),
    (187, "bpf_set_retval"),
    (188, "bpf_xdp_get_buff_len"),
    (189, "bpf_xdp_load_bytes"),
    (190, "bpf_xdp_store_bytes"),
    (191, "bpf_copy_from_user_task"),
    (192, "bpf_skb_set_tstamp"),
    (193, "bpf_ima_file_hash"),
    (194, "bpf_kptr_xchg"),
    (195, "bpf_map_lookup_percpu_elem"),
    (196, "bpf_skc_to_mptcp_sock"),
    (197, "bpf_dynptr_from_mem"),
    (198, "bpf_ringbuf_reserve_dynptr"),
    (199, "bpf_ringbuf_submit_dynptr"),
    (200, "bpf_ringbuf_discard_dynptr"),
    (201, "bpf_dynptr_read"),
    (202, "bpf_dynptr_write"),
    (203, "bpf_dynptr_data"),
    (204, "bpf_tcp_raw_gen_syncookie_ipv4"),
    (205, "bpf_tcp_raw_gen_syncookie_ipv6"),
    (206, "bpf_tcp_raw_check_syncookie_ipv4"),
    (207, "bpf_tcp_raw_check_syncookie_ipv6"),
    (208, "bpf_ktime_get_tai_ns"),
    (209, "bpf_user_ringbuf_drain"),
    (210, "bpf_cgrp_storage_get"),
    (211, "bpf_cgrp_storage_delete"),
];

/// The helper with this number, if the kernel has one. A program built
/// against a newer kernel than this table knows can call past its end, which
/// is why an unknown number is not an error.
pub fn helper(id: i32) -> Option<&'static str> {
    HELPERS.iter().find(|(n, _)| *n == id).map(|(_, name)| *name)
}
