//! Names for the numbers in a PE, generated by `node tools/petables.mjs`.
//!
//! Do not edit. These come from the `Formats` project that XPEViewer and
//! Detect It Easy are built on, at commit `7055c48738ba556f49e93ee490eb9d96ba143172`, and are used under its
//! MIT licence. The identifiers are that project's; the lower case reading of
//! them is this one's, to match how every other template here names a value.

/// ImageFileHeaderMachines, 40 named values.
pub const MACHINE: &[(i128, &str)] = &[
    (0x0, "unknown"),
    (0x14c, "i386"),
    (0x14d, "i486"),
    (0x14e, "pentium"),
    (0x160, "r3000 be"),
    (0x162, "r3000"),
    (0x166, "r4000"),
    (0x168, "r10000"),
    (0x169, "wcemipsv2"),
    (0x184, "alpha"),
    (0x1f0, "powerpc"),
    (0x1a2, "sh3"),
    (0x1a3, "sh3dsp"),
    (0x1a4, "sh3e"),
    (0x1a6, "sh4"),
    (0x1a8, "sh5"),
    (0x1c0, "arm"),
    (0x1c2, "thumb"),
    (0x1c4, "armnt"),
    (0x1d3, "am33"),
    (0x1f1, "powerpcfp"),
    (0x1f2, "powerpcbe"),
    (0x200, "ia64"),
    (0x266, "mips16"),
    (0x284, "alpha64"),
    (0x366, "mipsfpu"),
    (0x466, "mipsfpu16"),
    (0x520, "tricore"),
    (0xcef, "cef"),
    (0xebc, "ebc"),
    (0x5032, "riscv32"),
    (0x5064, "riscv64"),
    (0x5128, "riscv128"),
    (0x6232, "loongarch32"),
    (0x6264, "loongarch64"),
    (0x8664, "amd64"),
    (0x9041, "m32r"),
    (0xaa64, "arm64"),
    (0xc0ee, "cee"),
    (0xfd1d, "amd64 linux ni"),
];

/// ImageFileHeaderCharacteristics, 15 named bits.
pub const CHARACTERISTICS: &[(u32, &str)] = &[
    (0, "relocs stripped"),
    (1, "executable image"),
    (2, "line nums stripped"),
    (3, "local syms stripped"),
    (4, "aggresive ws trim"),
    (5, "large address aware"),
    (7, "bytes reversed lo"),
    (8, "32bit machine"),
    (9, "debug stripped"),
    (10, "removable run from swap"),
    (11, "net run from swap"),
    (12, "system"),
    (13, "dll"),
    (14, "up system only"),
    (15, "bytes reversed hi"),
];

/// ImageOptionalHeaderMagic, 3 named values.
pub const OPTIONAL_MAGIC: &[(i128, &str)] = &[
    (0x10b, "nt optional hdr32 magic"),
    (0x20b, "nt optional hdr64 magic"),
    (0x107, "rom optional hdr magic"),
];

/// ImageOptionalHeaderSubsystem, 14 named values.
pub const SUBSYSTEM: &[(i128, &str)] = &[
    (0x0, "unknown"),
    (0x1, "native"),
    (0x2, "windows gui"),
    (0x3, "windows cui"),
    (0x5, "os2 cui"),
    (0x7, "posix cui"),
    (0x8, "native windows"),
    (0x9, "windows ce gui"),
    (0xa, "efi application"),
    (0xb, "efi boot service driver"),
    (0xc, "efi runtime driver"),
    (0xd, "efi rom"),
    (0xe, "xbox"),
    (0x10, "windows boot application"),
];

/// ImageOptionalHeaderDllCharacteristics, 11 named bits.
pub const DLL_CHARACTERISTICS: &[(u32, &str)] = &[
    (5, "high entropy va"),
    (6, "dynamic base"),
    (7, "force integrity"),
    (8, "nx compat"),
    (9, "no isolation"),
    (10, "no seh"),
    (11, "no bind"),
    (12, "appcontainer"),
    (13, "wdm driver"),
    (14, "guard cf"),
    (15, "terminal server aware"),
];

/// ImageOptionalHeaderDataDirectory, 16 named values.
pub const DIRECTORY: &[(i128, &str)] = &[
    (0x0, "export"),
    (0x1, "import"),
    (0x2, "resource"),
    (0x3, "exception"),
    (0x4, "security"),
    (0x5, "basereloc"),
    (0x6, "debug"),
    (0x7, "architecture"),
    (0x8, "globalptr"),
    (0x9, "tls"),
    (0xa, "load config"),
    (0xb, "bound import"),
    (0xc, "iat"),
    (0xd, "delay import"),
    (0xe, "com descriptor"),
    (0xf, "reserved"),
];

/// ImageSectionHeaderFlags, 22 named bits.
pub const SECTION_FLAGS: &[(u32, &str)] = &[
    (3, "type no pad"),
    (5, "cnt code"),
    (6, "cnt initialized data"),
    (7, "cnt uninitialized data"),
    (8, "lnk other"),
    (9, "lnk info"),
    (11, "lnk remove"),
    (12, "lnk comdat"),
    (14, "no defer spec exc"),
    (15, "gprel"),
    (17, "mem purgeable"),
    (17, "mem 16bit"),
    (18, "mem locked"),
    (19, "mem preload"),
    (24, "lnk nreloc ovfl"),
    (25, "mem discardable"),
    (26, "mem not cached"),
    (27, "mem not paged"),
    (28, "mem shared"),
    (29, "mem execute"),
    (30, "mem read"),
    (31, "mem write"),
];

/// ImageRelBased, 11 named values.
pub const RELOCATION: &[(i128, &str)] = &[
    (0x0, "absolute"),
    (0x1, "high"),
    (0x2, "low"),
    (0x3, "highlow"),
    (0x4, "highadj"),
    (0x5, "machine specific 5"),
    (0x6, "reserved"),
    (0x7, "machine specific 7"),
    (0x8, "machine specific 8"),
    (0x9, "machine specific 9"),
    (0xa, "dir64"),
];

/// DebugTypes, 18 named values.
pub const DEBUG_TYPE: &[(i128, &str)] = &[
    (0x0, "unknown"),
    (0x1, "coff"),
    (0x2, "codeview"),
    (0x3, "fpo"),
    (0x4, "misc"),
    (0x5, "exception"),
    (0x6, "fixup"),
    (0x7, "omap to src"),
    (0x8, "omap from src"),
    (0x9, "borland"),
    (0xa, "reserved10"),
    (0xb, "clsid"),
    (0xc, "vc feature"),
    (0xd, "pogo"),
    (0xe, "iltcg"),
    (0xf, "mpx"),
    (0x10, "repro"),
    (0x14, "ex dllcharacteristics"),
];

/// ResourceTypes, 18 named values.
pub const RESOURCE_TYPE: &[(i128, &str)] = &[
    (0x1, "cursor"),
    (0x2, "bitmap"),
    (0x3, "icon"),
    (0x4, "menu"),
    (0x5, "dialog"),
    (0x6, "string"),
    (0x7, "fontdir"),
    (0x8, "font"),
    (0x9, "accelerators"),
    (0xa, "rcdata"),
    (0xb, "messagetable"),
    (0xc, "group cursor"),
    (0xe, "group icon"),
    (0xf, "nametable"),
    (0x10, "version"),
    (0x11, "dlginclude"),
    (0x17, "html"),
    (0x18, "manifest"),
];

/// ComImageFlags, 6 named bits.
pub const COM_IMAGE_FLAGS: &[(u32, &str)] = &[
    (0, "ilonly"),
    (1, "32bitrequired"),
    (2, "il library"),
    (3, "strongnamesigned"),
    (4, "native entrypoint"),
    (16, "trackdebugdata"),
];

